# Pesquisas {#intro}

You can label chapter and section titles using `{#label}` after them, e.g., we can reference Chapter \@ref(intro). If you do not manually label them, there will be automatic labels anyway, e.g., Chapter \@ref(methods).

Figures and tables with captions will be placed in `figure` and `table` environments, respectively.



Talvez uma das coisas mais importantes para se ter em mente neste livro é que ele foi, propositalmente, escrito de forma pouco linear. Apesar de toda metodologia estatística ser apresentada de forma estruturada, alguns capítulos fazem ampla interface com outros, mesmo que essa interface seja exposta de maneira incipente em função do interesse principal do momento. Por exemplo, o capítulo sobre o Teste T expõe uma pequena parte sobre modelos de regressão, conteúdo que somente é abordado posteriormente. Se em um primeiro momento isso pode gerar alguma (pequena) confusão, a releitura do capítulo após o término da sequência do livro frequentemente se traduz em um resultado mais positivo e uma melhor percepção da integração que existe entre diferentes modelos estatísticos. 
