---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Qui quadrado


```{r, include = FALSE }
load(file="~/anovabr/mqt/bases/Base R TDAH Arruda.RData")
library(tidyverse)
library(janitor)
library(knitr) #tables and graphs
library(kableExtra) #tables with different styles

library(descr) #chi squared
library(epitools) #epidemiology
```



Introdução


```{block, type="objectives"}
**Objetivos do capítulo**  
1. Introduzir o Qui quadrado
2. Realizar gráficos relacionados 
2. Apresentar os pressupostos do teste
3. Apresentar e interpretar métricas de tamanho do efeito
5. Dar exemplos relacionados à escrita dos resultados
```





## Pesquisa
  
<div class="alert alert-info" role="alert">
  <strong>Base: </strong> Base R TDAH Arruda
</div>  


## Execução no R

Como vem sendo ilustrado no decorrer do livro.

```{r}
ggplot(ds_selected, aes(x= sex_male, fill = adhd_parent)) +
  geom_bar(position = "fill") +
  coord_flip() +
  theme_bw() +
  labs(x = "sexo", y = "Proporção", fill = "TDAH")
```




```{r}
ds_selected %>%
  tabyl(sex_male, adhd_parent) %>%
  adorn_totals(c("row", "col")) %>%
  adorn_percentages("row") %>% 
  adorn_pct_formatting(rounding = "half up", digits = 0) %>%
  adorn_ns() 
```


```{r}
ds_selected %>% #<-- dataset with predictors
  count(adhd_parent) %>% 
  mutate(prop = prop.table(n)) %>% 
   adorn_totals()
```


Relação entre sexo (meninos e meninas) e apresentar TDAH (sim ou não)

```{r}
ds_selected %>% #Relative Risk for gender
  #drop_na() %>% 
  {CrossTable(.$sex_male,.$adhd_parent,
              expected = T,
              chisq = T)}
```


Risco

```{r}
#relative risk (boys)
riskratio(ds_selected$sex_male,ds_selected$adhd_parent) 
oddsratio(ds_selected$sex_male,ds_selected$adhd_parent, method =  "wald")
```

