# Quarta capa

Estatística é uma disciplina que, quase sempre, desperta uma preocupação em estudantes de ciências humanas, certamente não apenas aqueles matriculados em Psicologia. No entanto, em sentido oposto à ansiedade que essa disciplina pode provocar, há cada vez mais um reconhecimento sobre a importância de métodos e análises estatísticas no campo das ciências, especialmente nas áreas empíricas.

Neste livro, o Professor Luis Anunciação (PUC-Rio) se propõe a uma tarefa arriscada, mas muito pioneira: ensinar estatística e análise de dados através de pesquisas previamente publicadas na área da Psicologia e Epidemiologia, com dados abertos e acessíveis tanto para utilização no programa estatístico R e no JASP.

O livro consegue tocar em três aspectos essenciais em uma pesquisa, que são (1) como elaborar e estruturar uma pesquisa, (2) como analisar os dados decorrentes da pesquisa e tomar decisões probabilísticas e (3) como interpretar os resultados, integrando a modelagem estatística e as questões teóricas que, originalmente, motivaram à execução da pesquisa.

A leitura deste livro é bastante prazerosa. O conteúdo é passado de forma leve, sem sobrecarregar em aspectos matemáticos, mas também sem ignorá-los ou escondê-los. Na minha opinião, a forma utilizada para apresentar o conteúdo proposto é adequada e tende a agradar leitores de diferentes formações e interesses.

Anna Carolina de Almeida Portugal

Doutora em Fisiologia,

Professora da Universidade Federal do Rio de Janeiro (UFRJ)
