<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 12 Regressão linear múltipla | Métodos quantitativos em Psicologia com R</title>
  <meta name="description" content="This book was written for undergraduate level students on Quantitative Methods at the Pontifical Catholic University of Rio de Janeiro (PUC-Rio). The primary goal of this book is to provide a short and to-the-point exposition on the essentials of statistics. To a lesser degree, the mathematical modeling of statistical questions will be addressed. I expect this book can also help students who enroll for laboratory-based statistics and anyone who wants to learn R." />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 12 Regressão linear múltipla | Métodos quantitativos em Psicologia com R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book was written for undergraduate level students on Quantitative Methods at the Pontifical Catholic University of Rio de Janeiro (PUC-Rio). The primary goal of this book is to provide a short and to-the-point exposition on the essentials of statistics. To a lesser degree, the mathematical modeling of statistical questions will be addressed. I expect this book can also help students who enroll for laboratory-based statistics and anyone who wants to learn R." />
  <meta name="github-repo" content="cjvanlissa/gitbook-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 12 Regressão linear múltipla | Métodos quantitativos em Psicologia com R" />
  
  <meta name="twitter:description" content="This book was written for undergraduate level students on Quantitative Methods at the Pontifical Catholic University of Rio de Janeiro (PUC-Rio). The primary goal of this book is to provide a short and to-the-point exposition on the essentials of statistics. To a lesser degree, the mathematical modeling of statistical questions will be addressed. I expect this book can also help students who enroll for laboratory-based statistics and anyone who wants to learn R." />
  

<meta name="author" content="Luis Anunciação (PUC-Rio), PhD" />


<meta name="date" content="2021-01-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="regressão-linear-simples.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.6.1/grViz.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MQT em Psicologia com R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prefácio</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#apresentação"><i class="fa fa-check"></i><b>1.1</b> Apresentação</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#objetivo"><i class="fa fa-check"></i><b>1.2</b> Objetivo</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#público-alvo"><i class="fa fa-check"></i><b>1.3</b> Público-alvo</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#formato-do-livro"><i class="fa fa-check"></i><b>1.4</b> Formato do livro</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#bases"><i class="fa fa-check"></i><b>1.5</b> Bases</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#o-r"><i class="fa fa-check"></i><b>1.6</b> O R</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#pacotes-e-sintaxes"><i class="fa fa-check"></i><b>1.7</b> Pacotes e sintaxes</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#outros-recursos"><i class="fa fa-check"></i><b>1.8</b> Outros recursos</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html"><i class="fa fa-check"></i><b>2</b> Aspectos gerais</a><ul>
<li class="chapter" data-level="2.1" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#principais-áreas-da-estatística"><i class="fa fa-check"></i><b>2.1</b> Principais áreas da estatística</a></li>
<li class="chapter" data-level="2.2" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#considerações-sobre-escalas-de-medida-e-o-processo-de-mensuração-em-psicologia"><i class="fa fa-check"></i><b>2.2</b> Considerações sobre escalas de medida e o processo de mensuração em Psicologia</a><ul>
<li class="chapter" data-level="2.2.1" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#escala-nominal"><i class="fa fa-check"></i><b>2.2.1</b> Escala nominal</a></li>
<li class="chapter" data-level="2.2.2" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#escala-ordinal"><i class="fa fa-check"></i><b>2.2.2</b> Escala ordinal</a></li>
<li class="chapter" data-level="2.2.3" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#escala-intervalar"><i class="fa fa-check"></i><b>2.2.3</b> Escala intervalar</a></li>
<li class="chapter" data-level="2.2.4" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#escala-de-razão"><i class="fa fa-check"></i><b>2.2.4</b> Escala de razão</a></li>
<li class="chapter" data-level="2.2.5" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#síntese-das-características-de-cada-escala"><i class="fa fa-check"></i><b>2.2.5</b> Síntese das características de cada escala</a></li>
<li class="chapter" data-level="2.2.6" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#as-escalas-de-stevens-e-uma-tentativa-de-agrupamento"><i class="fa fa-check"></i><b>2.2.6</b> As escalas de Stevens e uma tentativa de agrupamento</a></li>
<li class="chapter" data-level="2.2.7" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#variáveis-discretas-ou-contínuas"><i class="fa fa-check"></i><b>2.2.7</b> Variáveis discretas ou contínuas</a></li>
<li class="chapter" data-level="2.2.8" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#hierarquia-da-classificação-e-a-importância-desses-conceitos-hoje-em-dia"><i class="fa fa-check"></i><b>2.2.8</b> Hierarquia da classificação e a importância desses conceitos hoje em dia</a></li>
<li class="chapter" data-level="2.2.9" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#em-qual-escala-devemos-classificar-os-testes-psicológicos"><i class="fa fa-check"></i><b>2.2.9</b> Em qual escala devemos classificar os testes psicológicos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="o-r-e-o-tidyverse.html"><a href="o-r-e-o-tidyverse.html"><i class="fa fa-check"></i><b>3</b> O R e o Tidyverse</a><ul>
<li class="chapter" data-level="3.1" data-path="o-r-e-o-tidyverse.html"><a href="o-r-e-o-tidyverse.html#tidyverse"><i class="fa fa-check"></i><b>3.1</b> Tidyverse</a></li>
<li class="chapter" data-level="3.2" data-path="o-r-e-o-tidyverse.html"><a href="o-r-e-o-tidyverse.html#verbos-do-dplyr"><i class="fa fa-check"></i><b>3.2</b> Verbos do dplyr</a></li>
<li class="chapter" data-level="3.3" data-path="o-r-e-o-tidyverse.html"><a href="o-r-e-o-tidyverse.html#resumo"><i class="fa fa-check"></i><b>3.3</b> Resumo</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html"><i class="fa fa-check"></i><b>4</b> Estatística Descritiva</a><ul>
<li class="chapter" data-level="4.1" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#pesquisa"><i class="fa fa-check"></i><b>4.1</b> Pesquisa</a></li>
<li class="chapter" data-level="4.2" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#condições-gerais"><i class="fa fa-check"></i><b>4.2</b> Condições gerais</a></li>
<li class="chapter" data-level="4.3" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#tabelas"><i class="fa fa-check"></i><b>4.3</b> Tabelas</a></li>
<li class="chapter" data-level="4.4" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#gráficos"><i class="fa fa-check"></i><b>4.4</b> Gráficos</a></li>
<li class="chapter" data-level="4.5" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variável-discreta"><i class="fa fa-check"></i><b>4.5</b> 1 variável discreta</a></li>
<li class="chapter" data-level="4.6" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variável-contínua"><i class="fa fa-check"></i><b>4.6</b> 1 variável contínua</a></li>
<li class="chapter" data-level="4.7" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variáveis-com-vi-discreta-e-vd-contínua"><i class="fa fa-check"></i><b>4.7</b> 2 variáveis com VI discreta (e VD contínua)</a></li>
<li class="chapter" data-level="4.8" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variáveis-com-vi-contínua-e-vd-contínua"><i class="fa fa-check"></i><b>4.8</b> 2 variáveis com VI contínua (e VD contínua)</a></li>
<li class="chapter" data-level="4.9" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#outros-gráficos-e-configurações"><i class="fa fa-check"></i><b>4.9</b> Outros gráficos e configurações</a></li>
<li class="chapter" data-level="4.10" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#resumo-1"><i class="fa fa-check"></i><b>4.10</b> Resumo</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="qui-quadrado.html"><a href="qui-quadrado.html"><i class="fa fa-check"></i><b>5</b> Qui quadrado</a><ul>
<li class="chapter" data-level="5.1" data-path="qui-quadrado.html"><a href="qui-quadrado.html#pesquisa-1"><i class="fa fa-check"></i><b>5.1</b> Pesquisa</a></li>
<li class="chapter" data-level="5.2" data-path="qui-quadrado.html"><a href="qui-quadrado.html#execução-no-r"><i class="fa fa-check"></i><b>5.2</b> Execução no R</a></li>
<li class="chapter" data-level="5.3" data-path="qui-quadrado.html"><a href="qui-quadrado.html#tamanho-do-efeito"><i class="fa fa-check"></i><b>5.3</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="5.4" data-path="qui-quadrado.html"><a href="qui-quadrado.html#execução-no-jasp"><i class="fa fa-check"></i><b>5.4</b> Execução no JASP</a></li>
<li class="chapter" data-level="5.5" data-path="qui-quadrado.html"><a href="qui-quadrado.html#escrita-dos-resultados"><i class="fa fa-check"></i><b>5.5</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="5.6" data-path="qui-quadrado.html"><a href="qui-quadrado.html#resumo-2"><i class="fa fa-check"></i><b>5.6</b> Resumo</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="teste-t.html"><a href="teste-t.html"><i class="fa fa-check"></i><b>6</b> Teste T</a><ul>
<li class="chapter" data-level="6.1" data-path="teste-t.html"><a href="teste-t.html#pesquisa-2"><i class="fa fa-check"></i><b>6.1</b> Pesquisa</a></li>
<li class="chapter" data-level="6.2" data-path="teste-t.html"><a href="teste-t.html#execução-no-r-1"><i class="fa fa-check"></i><b>6.2</b> Execução no R</a></li>
<li class="chapter" data-level="6.3" data-path="teste-t.html"><a href="teste-t.html#tamanho-do-efeito-1"><i class="fa fa-check"></i><b>6.3</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="6.4" data-path="teste-t.html"><a href="teste-t.html#execução-no-jasp-1"><i class="fa fa-check"></i><b>6.4</b> Execução no JASP</a></li>
<li class="chapter" data-level="6.5" data-path="teste-t.html"><a href="teste-t.html#escrita-dos-resultados-1"><i class="fa fa-check"></i><b>6.5</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="6.6" data-path="teste-t.html"><a href="teste-t.html#versão-robusta-do-teste-t"><i class="fa fa-check"></i><b>6.6</b> Versão robusta do Teste T</a><ul>
<li class="chapter" data-level="6.6.1" data-path="teste-t.html"><a href="teste-t.html#execução-no-r-2"><i class="fa fa-check"></i><b>6.6.1</b> Execução no R</a></li>
<li class="chapter" data-level="6.6.2" data-path="teste-t.html"><a href="teste-t.html#execução-no-jasp-2"><i class="fa fa-check"></i><b>6.6.2</b> Execução no JASP</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="teste-t.html"><a href="teste-t.html#mann-whitney"><i class="fa fa-check"></i><b>6.7</b> Mann-whitney</a><ul>
<li class="chapter" data-level="6.7.1" data-path="teste-t.html"><a href="teste-t.html#execução-no-r-3"><i class="fa fa-check"></i><b>6.7.1</b> Execução No R</a></li>
<li class="chapter" data-level="6.7.2" data-path="teste-t.html"><a href="teste-t.html#tamanho-do-efeito-2"><i class="fa fa-check"></i><b>6.7.2</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="6.7.3" data-path="teste-t.html"><a href="teste-t.html#execução-no-jasp-3"><i class="fa fa-check"></i><b>6.7.3</b> Execução no JASP</a></li>
<li class="chapter" data-level="6.7.4" data-path="teste-t.html"><a href="teste-t.html#escrita-dos-resultados-2"><i class="fa fa-check"></i><b>6.7.4</b> Escrita dos resultados</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="teste-t.html"><a href="teste-t.html#teste-t-e-regressão"><i class="fa fa-check"></i><b>6.8</b> Teste T e regressão</a></li>
<li class="chapter" data-level="6.9" data-path="teste-t.html"><a href="teste-t.html#resumo-3"><i class="fa fa-check"></i><b>6.9</b> Resumo</a></li>
<li class="chapter" data-level="6.10" data-path="teste-t.html"><a href="teste-t.html#pesquisas-adicionais"><i class="fa fa-check"></i><b>6.10</b> Pesquisas adicionais</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>7</b> ANOVA</a><ul>
<li class="chapter" data-level="7.1" data-path="anova.html"><a href="anova.html#legenda"><i class="fa fa-check"></i><b>7.1</b> Legenda</a></li>
<li class="chapter" data-level="7.2" data-path="anova.html"><a href="anova.html#pesquisa-3"><i class="fa fa-check"></i><b>7.2</b> Pesquisa</a></li>
<li class="chapter" data-level="7.3" data-path="anova.html"><a href="anova.html#anova-de-1-via"><i class="fa fa-check"></i><b>7.3</b> ANOVA de 1 via</a></li>
<li class="chapter" data-level="7.4" data-path="anova.html"><a href="anova.html#execução-no-r-4"><i class="fa fa-check"></i><b>7.4</b> Execução no R</a></li>
<li class="chapter" data-level="7.5" data-path="anova.html"><a href="anova.html#tamanho-do-efeito-3"><i class="fa fa-check"></i><b>7.5</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="7.6" data-path="anova.html"><a href="anova.html#execução-no-jasp-4"><i class="fa fa-check"></i><b>7.6</b> Execução no JASP</a></li>
<li class="chapter" data-level="7.7" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-3"><i class="fa fa-check"></i><b>7.7</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="7.8" data-path="anova.html"><a href="anova.html#post-hoc"><i class="fa fa-check"></i><b>7.8</b> Post hoc</a></li>
<li class="chapter" data-level="7.9" data-path="anova.html"><a href="anova.html#execução-no-r-5"><i class="fa fa-check"></i><b>7.9</b> Execução no R</a></li>
<li class="chapter" data-level="7.10" data-path="anova.html"><a href="anova.html#execução-no-jasp-5"><i class="fa fa-check"></i><b>7.10</b> Execução no JASP</a></li>
<li class="chapter" data-level="7.11" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-4"><i class="fa fa-check"></i><b>7.11</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="7.12" data-path="anova.html"><a href="anova.html#resumo-4"><i class="fa fa-check"></i><b>7.12</b> Resumo</a></li>
<li class="chapter" data-level="7.13" data-path="anova.html"><a href="anova.html#pesquisas-adicionais-1"><i class="fa fa-check"></i><b>7.13</b> Pesquisas adicionais</a></li>
<li class="chapter" data-level="7.14" data-path="anova.html"><a href="anova.html#pesquisa-4"><i class="fa fa-check"></i><b>7.14</b> Pesquisa</a></li>
<li class="chapter" data-level="7.15" data-path="anova.html"><a href="anova.html#anova-de-2-vias"><i class="fa fa-check"></i><b>7.15</b> ANOVA de 2 vias</a></li>
<li class="chapter" data-level="7.16" data-path="anova.html"><a href="anova.html#execução-no-r-6"><i class="fa fa-check"></i><b>7.16</b> Execução no R</a></li>
<li class="chapter" data-level="7.17" data-path="anova.html"><a href="anova.html#execução-no-jasp-6"><i class="fa fa-check"></i><b>7.17</b> Execução no JASP</a></li>
<li class="chapter" data-level="7.18" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-5"><i class="fa fa-check"></i><b>7.18</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="7.19" data-path="anova.html"><a href="anova.html#post-hoc-1"><i class="fa fa-check"></i><b>7.19</b> Post hoc</a></li>
<li class="chapter" data-level="7.20" data-path="anova.html"><a href="anova.html#execução-no-r-7"><i class="fa fa-check"></i><b>7.20</b> Execução no R</a></li>
<li class="chapter" data-level="7.21" data-path="anova.html"><a href="anova.html#execução-no-jasp-7"><i class="fa fa-check"></i><b>7.21</b> Execução no JASP</a></li>
<li class="chapter" data-level="7.22" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-6"><i class="fa fa-check"></i><b>7.22</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="7.23" data-path="anova.html"><a href="anova.html#resumo-5"><i class="fa fa-check"></i><b>7.23</b> Resumo</a></li>
<li class="chapter" data-level="7.24" data-path="anova.html"><a href="anova.html#anova-fatorial"><i class="fa fa-check"></i><b>7.24</b> ANOVA Fatorial</a></li>
<li class="chapter" data-level="7.25" data-path="anova.html"><a href="anova.html#execução-no-r-8"><i class="fa fa-check"></i><b>7.25</b> Execução no R</a></li>
<li class="chapter" data-level="7.26" data-path="anova.html"><a href="anova.html#execução-no-jasp-8"><i class="fa fa-check"></i><b>7.26</b> Execução no JASP</a></li>
<li class="chapter" data-level="7.27" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-7"><i class="fa fa-check"></i><b>7.27</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="7.28" data-path="anova.html"><a href="anova.html#resumo-6"><i class="fa fa-check"></i><b>7.28</b> Resumo</a></li>
<li class="chapter" data-level="7.29" data-path="anova.html"><a href="anova.html#post-hoc-2"><i class="fa fa-check"></i><b>7.29</b> Post hoc</a></li>
<li class="chapter" data-level="7.30" data-path="anova.html"><a href="anova.html#execução-no-jasp-9"><i class="fa fa-check"></i><b>7.30</b> Execução no JASP</a></li>
<li class="chapter" data-level="7.31" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-8"><i class="fa fa-check"></i><b>7.31</b> Escrita dos resultados</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html"><i class="fa fa-check"></i><b>8</b> ANOVA de medidas repetidas</a><ul>
<li class="chapter" data-level="8.1" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#pesquisa-5"><i class="fa fa-check"></i><b>8.1</b> Pesquisa</a></li>
<li class="chapter" data-level="8.2" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#execução-no-r-9"><i class="fa fa-check"></i><b>8.2</b> Execução no R</a></li>
<li class="chapter" data-level="8.3" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#tamanho-do-efeito-4"><i class="fa fa-check"></i><b>8.3</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="8.4" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#execução-no-jasp-10"><i class="fa fa-check"></i><b>8.4</b> Execução no JASP</a></li>
<li class="chapter" data-level="8.5" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#escrita-dos-resultados-9"><i class="fa fa-check"></i><b>8.5</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="8.6" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#resumo-7"><i class="fa fa-check"></i><b>8.6</b> Resumo</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="modelo-linear-misto.html"><a href="modelo-linear-misto.html"><i class="fa fa-check"></i><b>9</b> Modelo linear misto</a><ul>
<li class="chapter" data-level="9.1" data-path="modelo-linear-misto.html"><a href="modelo-linear-misto.html#pesquisa-6"><i class="fa fa-check"></i><b>9.1</b> Pesquisa</a></li>
<li class="chapter" data-level="9.2" data-path="modelo-linear-misto.html"><a href="modelo-linear-misto.html#execução-no-r-10"><i class="fa fa-check"></i><b>9.2</b> execução no R</a></li>
<li class="chapter" data-level="9.3" data-path="modelo-linear-misto.html"><a href="modelo-linear-misto.html#resumo-8"><i class="fa fa-check"></i><b>9.3</b> Resumo</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correlação.html"><a href="correlação.html"><i class="fa fa-check"></i><b>10</b> Correlação</a><ul>
<li class="chapter" data-level="10.1" data-path="correlação.html"><a href="correlação.html#pesquisa-7"><i class="fa fa-check"></i><b>10.1</b> Pesquisa</a></li>
<li class="chapter" data-level="10.2" data-path="correlação.html"><a href="correlação.html#execução-no-r-11"><i class="fa fa-check"></i><b>10.2</b> Execução no R</a></li>
<li class="chapter" data-level="10.3" data-path="correlação.html"><a href="correlação.html#resumo-9"><i class="fa fa-check"></i><b>10.3</b> Resumo</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html"><i class="fa fa-check"></i><b>11</b> Regressão linear simples</a><ul>
<li class="chapter" data-level="11.1" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#legenda-1"><i class="fa fa-check"></i><b>11.1</b> Legenda</a></li>
<li class="chapter" data-level="11.2" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#explicação-conceitual"><i class="fa fa-check"></i><b>11.2</b> Explicação conceitual</a></li>
<li class="chapter" data-level="11.3" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#pesquisa-8"><i class="fa fa-check"></i><b>11.3</b> Pesquisa</a></li>
<li class="chapter" data-level="11.4" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#execução-no-r-12"><i class="fa fa-check"></i><b>11.4</b> Execução no R</a></li>
<li class="chapter" data-level="11.5" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#resumo-10"><i class="fa fa-check"></i><b>11.5</b> Resumo</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html"><i class="fa fa-check"></i><b>12</b> Regressão linear múltipla</a><ul>
<li class="chapter" data-level="12.1" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#pesquisa-9"><i class="fa fa-check"></i><b>12.1</b> Pesquisa</a></li>
<li class="chapter" data-level="12.2" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#execução-no-r-13"><i class="fa fa-check"></i><b>12.2</b> Execução no R</a></li>
<li class="chapter" data-level="12.3" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#técnicas-automáticas-de-seleção-de-variáveis"><i class="fa fa-check"></i><b>12.3</b> Técnicas automáticas de seleção de variáveis</a></li>
<li class="chapter" data-level="12.4" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#resumo-11"><i class="fa fa-check"></i><b>12.4</b> Resumo</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="http://www.puc-rio.br/" target="blank">PUC-Rio</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Métodos quantitativos em Psicologia com R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regressão-linear-múltipla" class="section level1">
<h1><span class="header-section-number">Capítulo 12</span> Regressão linear múltipla</h1>
<p>Os modelos de regressão linear múltipla são desenvolvidos para predizer os valores médios de uma variável resposta (Y) em função de duas ou mais variáveis independentes (X). Nestes modelos, a VD deve ser contínua e as VIs podem ser tanto contínuas como categóricas. Tecnicamente, a família da ANOVA vista anteriormente são casos particulares de modelos de regressão múltipla.</p>
<p>Conceitualmente, neste modelo, se adiciona um outro preditor à equação vista no capítulo de regressão linear simples. Assim:</p>
<p><span class="math display">\[y_i = b_0 + b_1X{_1}_i + b_2X{_2}_i+ \epsilon_{i}\]</span></p>
<p><span class="math inline">\(y_i\)</span> representa a variável dependente<br />
<span class="math inline">\(b_0\)</span> é o intercepto (coeficiente linear)<br />
<span class="math inline">\(b_1\)</span> e <span class="math inline">\(b_2\)</span> indicam a inclinação dos preditores (coeficiente angular)<br />
<span class="math inline">\(\epsilon_{i}\)</span> é o erro/resíduo</p>
<p>Os seguintes pressupostos devem ser avaliados:</p>
<ol style="list-style-type: lower-roman">
<li>A relação entre as variáveis é linear</li>
<li>Os resíduos são independentes<br />
</li>
<li>Os resíduos são normalmente distribuídos</li>
<li>A variância dos resíduos é constante</li>
</ol>
<p>O mnemônico <u>LINE</u> (linearity, independence, normality, equal variance) talvez ajude a lembrar destes pressupostos.</p>
<div id="pesquisa-9" class="section level2">
<h2><span class="header-section-number">12.1</span> Pesquisa</h2>
<div class="alert alert-info" role="alert">
<p><strong>Base: </strong> Livro - Dados - Eating disorders</p>
</div>
<p>Vamos utilizar a pesquisa intitulada <a href="https://www.researchgate.net/publication/323729370_Aspects_Related_to_Body_Image_and_Eating_Behaviors_in_Healthy_Brazilian_Undergraduate_Students">“Aspects Related to Body Image and Eating Behaviors in Healthy Brazilian Undergraduate Students”</a>, publicada em 2018 no Global Journal of Educational Studies, que sou co-autor.</p>
<p>O objetivo dessa pesquisa foi explorar os fatores envolvidos em transtornos alimentares e aspectos da percepção da imagem corporal, bem como verificar a capacidade que uma medida possuia em predizer os resultados de outra. Esse artigo contou com a utilização de escalas aplicadas em 219 participantes no Brasil. Para acessar aspectos relacionados aos Transtornos alimentares, a escala EAT-26 foi aplicada. Para verificar aspectos da imagem corporal, a escala BSQ-34 foi aplicada.</p>
<p>Segue abaixo uma tabela inicial com dados descritivos dos resultados.</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="regressão-linear-múltipla.html#cb196-1"></a>dados_brasil <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb196-2"><a href="regressão-linear-múltipla.html#cb196-2"></a><span class="st">  </span><span class="kw">select</span>(sexo,eat_soma, bsq_soma, imc, faz_esporte, familia_esporte) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb196-3"><a href="regressão-linear-múltipla.html#cb196-3"></a><span class="st">  </span>psych<span class="op">::</span><span class="kw">describeBy</span>(.,<span class="dt">group =</span> <span class="st">&quot;sexo&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>pander<span class="op">::</span><span class="kw">pander</span>()</span></code></pre></div>
<pre><code>## Warning in pander.default(.): No pander.method for &quot;psych&quot;, reverting to
## default.No pander.method for &quot;describeBy&quot;, reverting to default.</code></pre>
<ul>
<li><p><strong>1</strong>:</p>
<table style="width:98%;">
<caption>Table continues below</caption>
<colgroup>
<col width="26%" />
<col width="8%" />
<col width="7%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="11%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">vars</th>
<th align="center">n</th>
<th align="center">mean</th>
<th align="center">sd</th>
<th align="center">median</th>
<th align="center">trimmed</th>
<th align="center">mad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>sexo</strong></td>
<td align="center">1</td>
<td align="center">126</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center"><strong>eat_soma</strong></td>
<td align="center">2</td>
<td align="center">126</td>
<td align="center">18.48</td>
<td align="center">10.09</td>
<td align="center">17</td>
<td align="center">17.9</td>
<td align="center">11.86</td>
</tr>
<tr class="odd">
<td align="center"><strong>bsq_soma</strong></td>
<td align="center">3</td>
<td align="center">126</td>
<td align="center">94.17</td>
<td align="center">34.87</td>
<td align="center">91</td>
<td align="center">92.64</td>
<td align="center">40.77</td>
</tr>
<tr class="even">
<td align="center"><strong>imc</strong></td>
<td align="center">4</td>
<td align="center">124</td>
<td align="center">22.58</td>
<td align="center">3.151</td>
<td align="center">21.95</td>
<td align="center">22.24</td>
<td align="center">2.542</td>
</tr>
<tr class="odd">
<td align="center"><strong>faz_esporte</strong></td>
<td align="center">5</td>
<td align="center">126</td>
<td align="center">0.4524</td>
<td align="center">0.4997</td>
<td align="center">0</td>
<td align="center">0.4412</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center"><strong>familia_esporte</strong></td>
<td align="center">6</td>
<td align="center">126</td>
<td align="center">0.4762</td>
<td align="center">0.5014</td>
<td align="center">0</td>
<td align="center">0.4706</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<table style="width:97%;">
<colgroup>
<col width="27%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="12%" />
<col width="13%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">min</th>
<th align="center">max</th>
<th align="center">range</th>
<th align="center">skew</th>
<th align="center">kurtosis</th>
<th align="center">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>sexo</strong></td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center"><strong>eat_soma</strong></td>
<td align="center">0</td>
<td align="center">47</td>
<td align="center">47</td>
<td align="center">0.4929</td>
<td align="center">-0.5091</td>
<td align="center">0.8988</td>
</tr>
<tr class="odd">
<td align="center"><strong>bsq_soma</strong></td>
<td align="center">32</td>
<td align="center">182</td>
<td align="center">150</td>
<td align="center">0.3512</td>
<td align="center">-0.4573</td>
<td align="center">3.107</td>
</tr>
<tr class="even">
<td align="center"><strong>imc</strong></td>
<td align="center">16.85</td>
<td align="center">32.87</td>
<td align="center">16.02</td>
<td align="center">0.9764</td>
<td align="center">0.8725</td>
<td align="center">0.2829</td>
</tr>
<tr class="odd">
<td align="center"><strong>faz_esporte</strong></td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">0.1891</td>
<td align="center">-1.98</td>
<td align="center">0.04452</td>
</tr>
<tr class="even">
<td align="center"><strong>familia_esporte</strong></td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">0.09421</td>
<td align="center">-2.007</td>
<td align="center">0.04467</td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>2</strong>:</p>
<table>
<caption>Table continues below</caption>
<colgroup>
<col width="27%" />
<col width="8%" />
<col width="6%" />
<col width="11%" />
<col width="11%" />
<col width="11%" />
<col width="12%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">vars</th>
<th align="center">n</th>
<th align="center">mean</th>
<th align="center">sd</th>
<th align="center">median</th>
<th align="center">trimmed</th>
<th align="center">mad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>sexo</strong></td>
<td align="center">1</td>
<td align="center">93</td>
<td align="center">2</td>
<td align="center">0</td>
<td align="center">2</td>
<td align="center">2</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center"><strong>eat_soma</strong></td>
<td align="center">2</td>
<td align="center">93</td>
<td align="center">12.65</td>
<td align="center">8.189</td>
<td align="center">11</td>
<td align="center">11.55</td>
<td align="center">5.93</td>
</tr>
<tr class="odd">
<td align="center"><strong>bsq_soma</strong></td>
<td align="center">3</td>
<td align="center">93</td>
<td align="center">64.24</td>
<td align="center">32.87</td>
<td align="center">55</td>
<td align="center">59.32</td>
<td align="center">19.27</td>
</tr>
<tr class="even">
<td align="center"><strong>imc</strong></td>
<td align="center">4</td>
<td align="center">90</td>
<td align="center">24.1</td>
<td align="center">3.99</td>
<td align="center">23.41</td>
<td align="center">23.65</td>
<td align="center">2.829</td>
</tr>
<tr class="odd">
<td align="center"><strong>faz_esporte</strong></td>
<td align="center">5</td>
<td align="center">93</td>
<td align="center">0.3978</td>
<td align="center">0.4921</td>
<td align="center">0</td>
<td align="center">0.3733</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center"><strong>familia_esporte</strong></td>
<td align="center">6</td>
<td align="center">92</td>
<td align="center">0.4783</td>
<td align="center">0.5023</td>
<td align="center">0</td>
<td align="center">0.473</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<table style="width:100%;">
<colgroup>
<col width="28%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="12%" />
<col width="14%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">min</th>
<th align="center">max</th>
<th align="center">range</th>
<th align="center">skew</th>
<th align="center">kurtosis</th>
<th align="center">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>sexo</strong></td>
<td align="center">2</td>
<td align="center">2</td>
<td align="center">0</td>
<td align="center">NA</td>
<td align="center">NA</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center"><strong>eat_soma</strong></td>
<td align="center">1</td>
<td align="center">50</td>
<td align="center">49</td>
<td align="center">1.688</td>
<td align="center">4.262</td>
<td align="center">0.8491</td>
</tr>
<tr class="odd">
<td align="center"><strong>bsq_soma</strong></td>
<td align="center">0</td>
<td align="center">188</td>
<td align="center">188</td>
<td align="center">1.504</td>
<td align="center">2.799</td>
<td align="center">3.408</td>
</tr>
<tr class="even">
<td align="center"><strong>imc</strong></td>
<td align="center">17.56</td>
<td align="center">39.21</td>
<td align="center">21.66</td>
<td align="center">1.269</td>
<td align="center">2.073</td>
<td align="center">0.4206</td>
</tr>
<tr class="odd">
<td align="center"><strong>faz_esporte</strong></td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">0.4107</td>
<td align="center">-1.851</td>
<td align="center">0.05103</td>
</tr>
<tr class="even">
<td align="center"><strong>familia_esporte</strong></td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">0.08562</td>
<td align="center">-2.014</td>
<td align="center">0.05236</td>
</tr>
</tbody>
</table></li>
</ul></li>
</ul>
<!-- end of list -->
</div>
<div id="execução-no-r-13" class="section level2">
<h2><span class="header-section-number">12.2</span> Execução no R</h2>
<p>Para crir o modelo no R, basta adicionar uma nova variável à equação. Neste caso, além de verificar o efeito da <u>percepção de imagem corporal</u>, o <u>peso</u> também irá ser utilizado como preditor. É importante notar que, por padrão, o R não usa linhas com dados ausentes e isso pode reduzir o poder do teste.</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="regressão-linear-múltipla.html#cb198-1"></a>mod_linear_multiplo &lt;-<span class="st"> </span><span class="kw">lm</span>(eat_soma <span class="op">~</span><span class="st"> </span>bsq_soma <span class="op">+</span><span class="st"> </span>peso_atual, <span class="dt">data =</span> dados_brasil)</span></code></pre></div>
<p>A apresentação segue o mesmo formato da realizada no capítulo específico de regressão linear simples.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="regressão-linear-múltipla.html#cb199-1"></a><span class="kw">ols_regress</span>(mod_linear_multiplo) </span></code></pre></div>
<pre><code>##                         Model Summary                          
## --------------------------------------------------------------
## R                       0.697       RMSE                7.082 
## R-Squared               0.486       Coef. Var          44.265 
## Adj. R-Squared          0.481       MSE                50.160 
## Pred R-Squared          0.472       MAE                 5.434 
## --------------------------------------------------------------
##  RMSE: Root Mean Square Error 
##  MSE: Mean Square Error 
##  MAE: Mean Absolute Error 
## 
##                                  ANOVA                                  
## -----------------------------------------------------------------------
##                  Sum of                                                
##                 Squares         DF    Mean Square       F         Sig. 
## -----------------------------------------------------------------------
## Regression    10099.820          2       5049.910    100.675    0.0000 
## Residual      10684.180        213         50.160                      
## Total         20784.000        215                                     
## -----------------------------------------------------------------------
## 
##                                   Parameter Estimates                                    
## ----------------------------------------------------------------------------------------
##       model      Beta    Std. Error    Std. Beta      t        Sig      lower     upper 
## ----------------------------------------------------------------------------------------
## (Intercept)     9.331         2.755                  3.386    0.001     3.899    14.762 
##    bsq_soma     0.180         0.013        0.678    13.811    0.000     0.155     0.206 
##  peso_atual    -0.121         0.037       -0.158    -3.221    0.001    -0.195    -0.047 
## ----------------------------------------------------------------------------------------</code></pre>
<p>Os resultados devem ser analisados de maneira cuidadosa. Inicialmente, é possível concluir que o modelo foi globalmente significativo (F(2, 213) = 100.675, p &lt; 0.001) e que cerca de 48% da variabilidade do EAT-26 pode ser atribuída aos valores do BSQ-34 e do peso do participante. Cada um dos preditores tem um comportamento específico. Em relação ao BSQ-34, cada unidade a mais em seu resultado impacta, em média, 0.18 pontos a mais no EAT-26, controlando pelo peso do participante (p &lt; 0.001). Além disso, cada 1 kg a mais no peso do participante impacta em -0.121 (p &lt; 0.001), em média, nos resultados do EAT-26, controlando pelos valores do BSQ-34.</p>
<p>A ideia de verificar o efeito de uma variável controlando por outra tem um significado particular. Assumindo duas pessoas que <u>tem o peso atual igual ao peso médio do grupo</u> ou <u>o mesmo peso</u>, cada ponto extra no BSQ gera, em média, 0.18 pontos a mais no EAT-26. Assim, o valor estimado no <u>EAT-26</u> de Um participante que teve 45 pontos no <u>BSQ</u> e <u>peso</u> de 66.51 (o peso médio) é de 9.41. Já o valor estimado no <u>EAT-26</u> de um outro participante com 46 pontos no <u>BSQ</u> e mesmo <u>peso</u> do primeiro participante (66.51) é de 9.59. A diferença entre os valores é exatamente igual ao coeficiente calculado na regressão (b = 0.18). Abaixo há duas linhas de código apresentando esses resultados.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="regressão-linear-múltipla.html#cb201-1"></a>peso_medio &lt;-<span class="st"> </span><span class="kw">mean</span>(dados_brasil<span class="op">$</span>peso_atual, <span class="dt">na.rm=</span>T)</span>
<span id="cb201-2"><a href="regressão-linear-múltipla.html#cb201-2"></a><span class="kw">predict</span>(mod_linear_multiplo, <span class="kw">data.frame</span>(<span class="dt">bsq_soma=</span><span class="kw">c</span>(<span class="dv">45</span>), <span class="dt">peso_atual=</span>peso_medio))</span></code></pre></div>
<pre><code>##        1 
## 9.416621</code></pre>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="regressão-linear-múltipla.html#cb203-1"></a><span class="kw">predict</span>(mod_linear_multiplo, <span class="kw">data.frame</span>(<span class="dt">bsq_soma=</span><span class="kw">c</span>(<span class="dv">46</span>), <span class="dt">peso_atual=</span>peso_medio))</span></code></pre></div>
<pre><code>##        1 
## 9.596919</code></pre>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="regressão-linear-múltipla.html#cb205-1"></a><span class="kw">predict</span>(mod_linear_multiplo, <span class="kw">data.frame</span>(<span class="dt">bsq_soma=</span><span class="kw">c</span>(<span class="dv">46</span>), <span class="dt">peso_atual=</span>peso_medio))<span class="op">-</span><span class="kw">predict</span>(mod_linear_multiplo, <span class="kw">data.frame</span>(<span class="dt">bsq_soma=</span><span class="kw">c</span>(<span class="dv">45</span>), <span class="dt">peso_atual=</span>peso_medio))</span></code></pre></div>
<pre><code>##         1 
## 0.1802979</code></pre>
<p>Tal como apresentado anteriores, a interpretação dos resultados depende da adequação de seus pressupostos. O relacionamento <u>linear</u> já havia sido investigado no gráfico de dispersão nos capítulos anteriores. A <u>Normalidade</u> dos resíduos pode ser vista pelo QQ-Plot (abaixo):</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="regressão-linear-múltipla.html#cb207-1"></a><span class="kw">ols_plot_resid_qq</span>(mod_linear_multiplo)</span></code></pre></div>
<p><img src="gitbook-demo_files/figure-html/unnamed-chunk-165-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="regressão-linear-múltipla.html#cb208-1"></a><span class="kw">ols_plot_resid_stud_fit</span>(mod_linear_multiplo)</span></code></pre></div>
<p><img src="gitbook-demo_files/figure-html/unnamed-chunk-165-2.png" width="672" style="display: block; margin: auto;" /></p>
<p>e por testes estatísticos formais. De forma análoga ao que aconteceu no capítulo de regressão linear simples, apesar de algo discordantes, o pressuposto de normalidade foi rejeitado.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="regressão-linear-múltipla.html#cb209-1"></a><span class="kw">ols_test_normality</span>(mod_linear_multiplo)</span></code></pre></div>
<pre><code>## Warning in ks.test(y, &quot;pnorm&quot;, mean(y), sd(y)): ties should not be present for
## the Kolmogorov-Smirnov test</code></pre>
<pre><code>## -----------------------------------------------
##        Test             Statistic       pvalue  
## -----------------------------------------------
## Shapiro-Wilk              0.9607         0.0000 
## Kolmogorov-Smirnov        0.0689         0.2567 
## Cramer-von Mises         17.7972         0.0000 
## Anderson-Darling          2.2135         0.0000 
## -----------------------------------------------</code></pre>
<p>A <u>independência</u> dos resíduos pode ser avaliada pelo Durbin Watson. É importante lemrbar que a Hipótees nula é de que os resíduos não são correlacionados.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="regressão-linear-múltipla.html#cb212-1"></a>car<span class="op">::</span><span class="kw">durbinWatsonTest</span>(mod_linear_multiplo)</span></code></pre></div>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1      0.02410462      1.947272   0.642
##  Alternative hypothesis: rho != 0</code></pre>
<p>As homocedasticidade, ou seja, <u>variâncias constantes</u> pode ser vista em um gráfico de dispersão dos resíduos (residual) contra os valores previstos (fitted).</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="regressão-linear-múltipla.html#cb214-1"></a><span class="kw">ols_plot_resid_fit</span>(mod_linear_multiplo)</span></code></pre></div>
<p><img src="gitbook-demo_files/figure-html/unnamed-chunk-168-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>O teste Breusch-Pagan também é um indicador importante e a Hipótese nula assume homocedasticidade. Portanto, a estatística de teste deveria ser insignificante para que a homocedasticidade pudeSSR ser aceita, o que não é o caso aqui.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="regressão-linear-múltipla.html#cb215-1"></a><span class="kw">ols_test_breusch_pagan</span>(mod_linear_multiplo)</span></code></pre></div>
<pre><code>## 
##  Breusch Pagan Test for Heteroskedasticity
##  -----------------------------------------
##  Ho: the variance is constant            
##  Ha: the variance is not constant        
## 
##                 Data                 
##  ------------------------------------
##  Response : eat_soma 
##  Variables: fitted values of eat_soma 
## 
##         Test Summary          
##  -----------------------------
##  DF            =    1 
##  Chi2          =    5.723583 
##  Prob &gt; Chi2   =    0.01673854</code></pre>
<p>Como esse modelo pode reunir diversas variáveis independentes, é importante verificar o quanto elas são correlacionadas entre si. Isso é feito pela análise de Variance Inflaction Factor (VIF). Valores de VIF superiores a 4 indicam que as variáveis indepenentes são fortemente correlacionadas e, com isso, as estimativas podem ser distorcidas. Neste caso, isso não aconteceu.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="regressão-linear-múltipla.html#cb217-1"></a><span class="kw">ols_coll_diag</span>(mod_linear_multiplo)</span></code></pre></div>
<pre><code>## Tolerance and Variance Inflation Factor
## ---------------------------------------
##    Variables Tolerance      VIF
## 1   bsq_soma 0.9999925 1.000007
## 2 peso_atual 0.9999925 1.000007
## 
## 
## Eigenvalue and Condition Index
## ------------------------------
##   Eigenvalue Condition Index   intercept   bsq_soma  peso_atual
## 1 2.85848875        1.000000 0.003656276 0.01908105 0.004257786
## 2 0.12424761        4.796498 0.027440631 0.92248915 0.062344260
## 3 0.01726365       12.867732 0.968903094 0.05842980 0.933397954</code></pre>
<p>Com isso realizado, os diagnósticos indicaram que a normalidade e a homocedasticidade foram violadas, novamente sugerindo uma interpretação cautelosa dos resultados. Abaixo uma orientação de como escrever os resultados.</p>
<div class="writing">
<p>
<strong>Como escrever os resultados</strong>
</p>
<p>
Um modelo de regressão múltipla foi calculado para verificar os resultados dos comportamentos alimentares (EAT-26) em função da percepção de imagem corporal (BSQ-34) e do peso do participante. Os resultados indicaram que cerca de 48% da variância do EAT-26 pode ser atribuída aos preditores (R2 = 0.486, F(2,213) = 100.675, p &lt; 0.001). Cada ponto a mais no BSQ-34 impacta, em média, em 0.180 no EAT-26 (p &lt; 0.001), controlando pelo peso do participante.
</p>
</div>
</div>
<div id="técnicas-automáticas-de-seleção-de-variáveis" class="section level2">
<h2><span class="header-section-number">12.3</span> Técnicas automáticas de seleção de variáveis</h2>
<p>Os critérios para composição dos modelos costuma despertar um grande interesse nos debates estatísticos e quantas, quais e como eleger as variáveis independentes é um dos mais intensos. A seleção destas variáveis visa otimizar a acurácia do modelo, mas sem perder sua parcimônia, ou seja, simplicidade <span class="citation">(Gaudio &amp; Zandonade, <a href="#ref-Gaudio2001" role="doc-biblioref">2001</a>; Unger &amp; Hansch, <a href="#ref-Unger1973" role="doc-biblioref">1973</a>)</span>. Métodos com justificativa teórica costumam ser chamados de entrada bruta, enquanto métodos em que se implementa algum algorítimo computadorizado para tal seleção tendem a ser denominados de métodos automáticos. Apesar do detalhamento destas técnicas ser fora do escopo dete capítulo, a seguir são listadas as principais técnicas:</p>
<ol style="list-style-type: decimal">
<li>Backward selection<br />
</li>
<li>Forward selection<br />
</li>
<li>Stepwise selecion<br />
</li>
<li>Lasso selection</li>
</ol>
</div>
<div id="resumo-11" class="section level2">
<h2><span class="header-section-number">12.4</span> Resumo</h2>
<ol style="list-style-type: decimal">
<li>O termo regressão múltipla se refere a um modelo de regressão com duas ou mais variáveis independentes<br />
</li>
<li>As VIs podem ser de qualquer natureza, o que significa que toda família da ANOVA pode ser entendida como casos particulares de regressão<br />
</li>
<li>Os diagnósticos são os mesmos dos modelos simples, mas agora é necessário também testar a multicolinearidade do modelo<br />
</li>
<li>Existem diferentes métodos para adicionar preditores e maneiras manuais e automáticas são disponíveis</li>
</ol>

<div id="refs" class="references">
<div>
<p>BAIRD, D. (1983). The fisher/pearson chi-squared controversy: A turning point for inductive inference. <em>The British Journal for the Philosophy of Science</em>, <em>34</em>(2), 105–118. <a href="https://doi.org/10.1093/bjps/34.2.105">https://doi.org/10.1093/bjps/34.2.105</a></p>
</div>
<div>
<p>Barker, L. E., &amp; Shaw, K. M. (2015). Best (but oft-forgotten) practices: Checking assumptions concerning regression residuals. <em>The American Journal of Clinical Nutrition</em>, <em>102</em>(3), 533–539. <a href="https://doi.org/10.3945/ajcn.115.113498">https://doi.org/10.3945/ajcn.115.113498</a></p>
</div>
<div>
<p>Borgatta, E. F., &amp; Bohrnstedt, G. W. (1980). Level of measurement. <em>Sociological Methods &amp; Research</em>, <em>9</em>(2), 147–160. <a href="https://doi.org/10.1177/004912418000900202">https://doi.org/10.1177/004912418000900202</a></p>
</div>
<div>
<p>Chartier, S., &amp; Faulkner, A. (2008). General linear models: An integrated approach to statistics. <em>Tutorials in Quantitative Methods for Psychology</em>, <em>4</em>(2), 65–78. <a href="https://doi.org/10.20982/tqmp.04.2.p065">https://doi.org/10.20982/tqmp.04.2.p065</a></p>
</div>
<div>
<p>Cohen, J. (1988). <em>Statistical power analysis for the behavioral sciences</em>. Routledge. <a href="https://doi.org/10.4324/9780203771587">https://doi.org/10.4324/9780203771587</a></p>
</div>
<div>
<p>Ernst, A. F., &amp; Albers, C. J. (2017). Regression assumptions in clinical psychology research practicea systematic review of common misconceptions. <em>PeerJ</em>, <em>5</em>, e3323. <a href="https://doi.org/10.7717/peerj.3323">https://doi.org/10.7717/peerj.3323</a></p>
</div>
<div>
<p>Field, A. P., &amp; Wilcox, R. R. (2017). Robust statistical methods: A primer for clinical psychology and experimental psychopathology researchers. <em>Behaviour Research and Therapy</em>, <em>98</em>, 19–38. <a href="https://doi.org/10.1016/j.brat.2017.05.013">https://doi.org/10.1016/j.brat.2017.05.013</a></p>
</div>
<div>
<p>Gaudio, A. C., &amp; Zandonade, E. (2001). Proposição, validação e análise dos modelos que correlacionam estrutura química e atividade biológica. <em>Quimica Nova</em>, <em>24</em>(5), 658–671. <a href="https://doi.org/10.1590/s0100-40422001000500013">https://doi.org/10.1590/s0100-40422001000500013</a></p>
</div>
<div>
<p>Gueorguieva, R., &amp; Krystal, J. H. (2004). Move over ANOVA. <em>Archives of General Psychiatry</em>, <em>61</em>(3), 310. <a href="https://doi.org/10.1001/archpsyc.61.3.310">https://doi.org/10.1001/archpsyc.61.3.310</a></p>
</div>
<div>
<p>Howell, D. C. (2011). <em>Fundamental Statistics for the Behavioral Sciences</em>. Wadsworth Cengage Learning.</p>
</div>
<div>
<p>Howell, D. C. (2011). <em>Fundamental statistics for the behavioral sciences (7th edition)</em>. Belmont.</p>
</div>
<div>
<p>Krus, D. J., &amp; Krus, P. H. (1977). Lost: McCalls t scores: Why? <em>Educational and Psychological Measurement</em>, <em>37</em>(1), 257–261. <a href="https://doi.org/10.1177/001316447703700134">https://doi.org/10.1177/001316447703700134</a></p>
</div>
<div>
<p>Lix, L. M., Keselman, J. C., &amp; Keselman, H. J. (1996). Consequences of assumption violations revisited: A quantitative review of alternatives to the one-way analysis of variance "f" test. <em>Review of Educational Research</em>, <em>66</em>(4), 579. <a href="https://doi.org/10.2307/1170654">https://doi.org/10.2307/1170654</a></p>
</div>
<div>
<p>Lumley, T., Diehr, P., Emerson, S., &amp; Chen, L. (2002). The importance of the normality assumption in large public health data sets. <em>Annual Review of Public Health</em>, <em>23</em>(1), 151–169. <a href="https://doi.org/10.1146/annurev.publhealth.23.100901.140546">https://doi.org/10.1146/annurev.publhealth.23.100901.140546</a></p>
</div>
<div>
<p>Michell, J. (1993). The origins of the representational theory of measurement: Helmholtz, hölder, and russell. <em>Studies in History and Philosophy of Science Part A</em>, <em>24</em>(2), 185–206. <a href="https://doi.org/10.1016/0039-3681(93)90045-l">https://doi.org/10.1016/0039-3681(93)90045-l</a></p>
</div>
<div>
<p>Morettin, P. A., &amp; Bussab, W. de O. (2010). <em>Estatistica basica</em>. Saraiva.</p>
</div>
<div>
<p>Pearson, K. (1900). X. On the criterion that a given system of deviations from the probable in the case of a correlated system of variables is such that it can be reasonably supposed to have arisen from random sampling. <em>The London, Edinburgh, and Dublin Philosophical Magazine and Journal of Science</em>, <em>50</em>(302), 157–175. <a href="https://doi.org/10.1080/14786440009463897">https://doi.org/10.1080/14786440009463897</a></p>
</div>
<div>
<p>Privitera, G. J. (2016). <em>Statistics for the behavioral sciences</em>. SAGE.</p>
</div>
<div>
<p>Quené, H., &amp; Bergh, H. van den. (2004). On multi-level modeling of data from repeated measures designs: A tutorial. <em>Speech Communication</em>, <em>43</em>(1-2), 103–121. <a href="https://doi.org/10.1016/j.specom.2004.02.004">https://doi.org/10.1016/j.specom.2004.02.004</a></p>
</div>
<div>
<p>Smart, J. C. (1999). <em>Higher education: Handbook of theory and research</em>. Springer.</p>
</div>
<div>
<p>Stevens, S. S. (1959). Measurement, psychophysics, and utility. In P. Churchman C. W. &amp; Ratoosh (Ed.), <em>Measurement: Definitions and theories</em> (pp. 18–63). Willey.</p>
</div>
<div>
<p>Stevens, S. S. (1946). On the theory of scales of measurement. <em>Science</em>, <em>103</em>(2684), 677–680. <a href="https://doi.org/10.1126/science.103.2684.677">https://doi.org/10.1126/science.103.2684.677</a></p>
</div>
<div>
<p>Thorndike, E. L. (1914). <em>Educational psychology, vol 3: Mental work and fatigue and individual differences and their causes.</em> Teachers College. <a href="https://doi.org/10.1037/13796-000">https://doi.org/10.1037/13796-000</a></p>
</div>
<div>
<p>Unger, S. H., &amp; Hansch, C. (1973). Model building in structure-activity relations. Reexamination of adrenergic blocking activity of .Beta.-halo-.beta.-arylalkylamines. <em>Journal of Medicinal Chemistry</em>, <em>16</em>(7), 745–749. <a href="https://doi.org/10.1021/jm00265a001">https://doi.org/10.1021/jm00265a001</a></p>
</div>
<div>
<p>Velleman, P. F., &amp; Wilkinson, L. (1993). Nominal, ordinal, interval, and ratio typologies are misleading. <em>The American Statistician</em>, <em>47</em>(1), 65–72. <a href="https://doi.org/10.1080/00031305.1993.10475938">https://doi.org/10.1080/00031305.1993.10475938</a></p>
</div>
<div>
<p>Wasserstein, R. L., &amp; Lazar, N. A. (2016). The ASA statement on p-values: Context, process, and purpose. <em>The American Statistician</em>, <em>70</em>(2), 129–133. <a href="https://doi.org/10.1080/00031305.2016.1154108">https://doi.org/10.1080/00031305.2016.1154108</a></p>
</div>
<div>
<p>Wu, H., &amp; Leung, S.-O. (2017). Can likert scales be treated as interval scales?A simulation study. <em>Journal of Social Service Research</em>, <em>43</em>(4), 527–532. <a href="https://doi.org/10.1080/01488376.2017.1329775">https://doi.org/10.1080/01488376.2017.1329775</a></p>
</div>
<div>
<p>Yap, B. W., &amp; Sim, C. H. (2011). Comparisons of various types of normality tests. <em>Journal of Statistical Computation and Simulation</em>, <em>81</em>(12), 2141–2155. <a href="https://doi.org/10.1080/00949655.2010.520163">https://doi.org/10.1080/00949655.2010.520163</a></p>
</div>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Gaudio2001">
<p>Gaudio, A. C., &amp; Zandonade, E. (2001). Proposição, validação e análise dos modelos que correlacionam estrutura química e atividade biológica. <em>Quimica Nova</em>, <em>24</em>(5), 658–671. <a href="https://doi.org/10.1590/s0100-40422001000500013">https://doi.org/10.1590/s0100-40422001000500013</a></p>
</div>
<div id="ref-Unger1973">
<p>Unger, S. H., &amp; Hansch, C. (1973). Model building in structure-activity relations. Reexamination of adrenergic blocking activity of .Beta.-halo-.beta.-arylalkylamines. <em>Journal of Medicinal Chemistry</em>, <em>16</em>(7), 745–749. <a href="https://doi.org/10.1021/jm00265a001">https://doi.org/10.1021/jm00265a001</a></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="regressão-linear-simples.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/cjvanlissa/gitbook-demo/edit/master/11-regressao_linear_multipla.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["gitbook-demo.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
