<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Cap. 15 Regressão logística binária | Métodos quantitativos em Psicologia com R</title>
  <meta name="description" content="This book was written for undergraduate level students on Quantitative Methods at the Pontifical Catholic University of Rio de Janeiro (PUC-Rio). The primary goal of this book is to provide a short and to-the-point exposition on the essentials of statistics. To a lesser degree, the mathematical modeling of statistical questions will be addressed. I expect this book can also help students who enroll for laboratory-based statistics and anyone who wants to learn R." />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="Cap. 15 Regressão logística binária | Métodos quantitativos em Psicologia com R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book was written for undergraduate level students on Quantitative Methods at the Pontifical Catholic University of Rio de Janeiro (PUC-Rio). The primary goal of this book is to provide a short and to-the-point exposition on the essentials of statistics. To a lesser degree, the mathematical modeling of statistical questions will be addressed. I expect this book can also help students who enroll for laboratory-based statistics and anyone who wants to learn R." />
  <meta name="github-repo" content="cjvanlissa/gitbook-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Cap. 15 Regressão logística binária | Métodos quantitativos em Psicologia com R" />
  
  <meta name="twitter:description" content="This book was written for undergraduate level students on Quantitative Methods at the Pontifical Catholic University of Rio de Janeiro (PUC-Rio). The primary goal of this book is to provide a short and to-the-point exposition on the essentials of statistics. To a lesser degree, the mathematical modeling of statistical questions will be addressed. I expect this book can also help students who enroll for laboratory-based statistics and anyone who wants to learn R." />
  

<meta name="author" content="Luis Anunciação (PUC-Rio), PhD" />


<meta name="date" content="2021-02-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="regressão-linear-múltipla.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="lab.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MQT em Psicologia com R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prefácio</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#a-proposta"><i class="fa fa-check"></i><b>1.1</b> A proposta</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#objetivo"><i class="fa fa-check"></i><b>1.2</b> Objetivo</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#público-alvo"><i class="fa fa-check"></i><b>1.3</b> Público-alvo</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#formato-do-livro"><i class="fa fa-check"></i><b>1.4</b> Formato do livro</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#como-usar-este-livro"><i class="fa fa-check"></i><b>1.5</b> Como usar este livro</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#bases-de-dados"><i class="fa fa-check"></i><b>1.6</b> Bases de dados</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#o-r-e-os-pacotes"><i class="fa fa-check"></i><b>1.7</b> O R e os pacotes</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#jasp"><i class="fa fa-check"></i><b>1.8</b> JASP</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#outros-recursos"><i class="fa fa-check"></i><b>1.9</b> Outros recursos</a></li>
<li class="chapter" data-level="1.10" data-path="index.html"><a href="index.html#preço"><i class="fa fa-check"></i><b>1.10</b> Preço</a></li>
<li class="chapter" data-level="1.11" data-path="index.html"><a href="index.html#capa"><i class="fa fa-check"></i><b>1.11</b> Capa</a></li>
<li class="chapter" data-level="1.12" data-path="index.html"><a href="index.html#versão-do-livro"><i class="fa fa-check"></i><b>1.12</b> Versão do livro</a></li>
<li class="chapter" data-level="1.13" data-path="index.html"><a href="index.html#agradecimentos-e-revisões-técnicas"><i class="fa fa-check"></i><b>1.13</b> Agradecimentos e revisões técnicas</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="programas-estatísticos.html"><a href="programas-estatísticos.html"><i class="fa fa-check"></i><b>2</b> Programas estatísticos</a><ul>
<li class="chapter" data-level="2.1" data-path="programas-estatísticos.html"><a href="programas-estatísticos.html#o-r"><i class="fa fa-check"></i><b>2.1</b> O R</a></li>
<li class="chapter" data-level="2.2" data-path="programas-estatísticos.html"><a href="programas-estatísticos.html#tidyverse"><i class="fa fa-check"></i><b>2.2</b> Tidyverse</a></li>
<li class="chapter" data-level="2.3" data-path="programas-estatísticos.html"><a href="programas-estatísticos.html#dificuldades-esperadas"><i class="fa fa-check"></i><b>2.3</b> Dificuldades esperadas</a></li>
<li class="chapter" data-level="2.4" data-path="programas-estatísticos.html"><a href="programas-estatísticos.html#verbos-do-dplyr"><i class="fa fa-check"></i><b>2.4</b> Verbos do dplyr</a></li>
<li class="chapter" data-level="2.5" data-path="programas-estatísticos.html"><a href="programas-estatísticos.html#o-jasp"><i class="fa fa-check"></i><b>2.5</b> O JASP</a></li>
<li class="chapter" data-level="2.6" data-path="programas-estatísticos.html"><a href="programas-estatísticos.html#resumo"><i class="fa fa-check"></i><b>2.6</b> Resumo</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html"><i class="fa fa-check"></i><b>3</b> Aspectos gerais</a><ul>
<li class="chapter" data-level="3.1" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#os-objetivos-de-uma-pesquisa"><i class="fa fa-check"></i><b>3.1</b> Os objetivos de uma pesquisa</a></li>
<li class="chapter" data-level="3.2" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#a-dimensão-temporal-de-uma-pesquisa"><i class="fa fa-check"></i><b>3.2</b> A dimensão temporal de uma pesquisa</a></li>
<li class="chapter" data-level="3.3" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#conceitos-fundamentais"><i class="fa fa-check"></i><b>3.3</b> conceitos fundamentais</a><ul>
<li class="chapter" data-level="3.3.1" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#modelos-científicos"><i class="fa fa-check"></i><b>3.3.1</b> Modelos científicos</a></li>
<li class="chapter" data-level="3.3.2" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#variáveis"><i class="fa fa-check"></i><b>3.3.2</b> Variáveis</a></li>
<li class="chapter" data-level="3.3.3" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#delineamentos-de-pesquisa"><i class="fa fa-check"></i><b>3.3.3</b> Delineamentos de pesquisa</a></li>
<li class="chapter" data-level="3.3.4" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#delineamentos-observacionais-e-correlacionais"><i class="fa fa-check"></i><b>3.3.4</b> Delineamentos observacionais (e correlacionais)</a></li>
<li class="chapter" data-level="3.3.5" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#delineamentos-experimentais"><i class="fa fa-check"></i><b>3.3.5</b> Delineamentos experimentais</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#considerações-sobre-escalas-de-medida-e-o-processo-de-mensuração-em-psicologia"><i class="fa fa-check"></i><b>3.4</b> Considerações sobre escalas de medida e o processo de mensuração em Psicologia</a><ul>
<li class="chapter" data-level="3.4.1" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#escala-nominal"><i class="fa fa-check"></i><b>3.4.1</b> Escala nominal</a></li>
<li class="chapter" data-level="3.4.2" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#escala-ordinal"><i class="fa fa-check"></i><b>3.4.2</b> Escala ordinal</a></li>
<li class="chapter" data-level="3.4.3" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#escala-intervalar"><i class="fa fa-check"></i><b>3.4.3</b> Escala intervalar</a></li>
<li class="chapter" data-level="3.4.4" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#escala-de-razão"><i class="fa fa-check"></i><b>3.4.4</b> Escala de razão</a></li>
<li class="chapter" data-level="3.4.5" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#síntese-das-características-de-cada-escala"><i class="fa fa-check"></i><b>3.4.5</b> Síntese das características de cada escala</a></li>
<li class="chapter" data-level="3.4.6" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#as-escalas-de-stevens-e-uma-tentativa-de-agrupamento"><i class="fa fa-check"></i><b>3.4.6</b> As escalas de Stevens e uma tentativa de agrupamento</a></li>
<li class="chapter" data-level="3.4.7" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#variáveis-discretas-ou-contínuas"><i class="fa fa-check"></i><b>3.4.7</b> Variáveis discretas ou contínuas</a></li>
<li class="chapter" data-level="3.4.8" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#hierarquia-da-classificação-e-a-importância-desses-conceitos-hoje-em-dia"><i class="fa fa-check"></i><b>3.4.8</b> Hierarquia da classificação e a importância desses conceitos hoje em dia</a></li>
<li class="chapter" data-level="3.4.9" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#em-qual-escala-devemos-classificar-os-testes-psicológicos"><i class="fa fa-check"></i><b>3.4.9</b> Em qual escala devemos classificar os testes psicológicos</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#principais-áreas-da-estatística"><i class="fa fa-check"></i><b>3.5</b> Principais áreas da estatística</a></li>
<li class="chapter" data-level="3.6" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#resumo-1"><i class="fa fa-check"></i><b>3.6</b> Resumo</a></li>
<li class="chapter" data-level="3.7" data-path="aspectos-gerais.html"><a href="aspectos-gerais.html#questões"><i class="fa fa-check"></i><b>3.7</b> Questões</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html"><i class="fa fa-check"></i><b>4</b> Estatística Descritiva</a><ul>
<li class="chapter" data-level="4.1" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#tabelas"><i class="fa fa-check"></i><b>4.1</b> Tabelas</a></li>
<li class="chapter" data-level="4.2" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#gráficos"><i class="fa fa-check"></i><b>4.2</b> Gráficos</a></li>
<li class="chapter" data-level="4.3" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#medidas-de-posição-e-dispersão"><i class="fa fa-check"></i><b>4.3</b> Medidas de posição e dispersão</a></li>
<li class="chapter" data-level="4.4" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#média"><i class="fa fa-check"></i><b>4.4</b> Média</a></li>
<li class="chapter" data-level="4.5" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#mediana"><i class="fa fa-check"></i><b>4.5</b> Mediana</a></li>
<li class="chapter" data-level="4.6" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#moda"><i class="fa fa-check"></i><b>4.6</b> Moda</a></li>
<li class="chapter" data-level="4.7" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#amplitude"><i class="fa fa-check"></i><b>4.7</b> Amplitude</a></li>
<li class="chapter" data-level="4.8" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#amplitude-interquartil"><i class="fa fa-check"></i><b>4.8</b> Amplitude interquartil</a></li>
<li class="chapter" data-level="4.9" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variância-e-desvio-padrão"><i class="fa fa-check"></i><b>4.9</b> Variância e Desvio-padrão</a></li>
<li class="chapter" data-level="4.10" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#pesquisa"><i class="fa fa-check"></i><b>4.10</b> Pesquisa</a></li>
<li class="chapter" data-level="4.11" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#execução-no-r"><i class="fa fa-check"></i><b>4.11</b> Execução no R</a></li>
<li class="chapter" data-level="4.12" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#gráficos-1"><i class="fa fa-check"></i><b>4.12</b> Gráficos</a></li>
<li class="chapter" data-level="4.13" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variável-discreta"><i class="fa fa-check"></i><b>4.13</b> 1 variável discreta</a></li>
<li class="chapter" data-level="4.14" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variável-contínua"><i class="fa fa-check"></i><b>4.14</b> 1 variável contínua</a></li>
<li class="chapter" data-level="4.15" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variáveis-com-vi-discreta-e-vd-contínua"><i class="fa fa-check"></i><b>4.15</b> 2 variáveis com VI discreta (e VD contínua)</a></li>
<li class="chapter" data-level="4.16" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variáveis-com-vi-contínua-e-vd-contínua"><i class="fa fa-check"></i><b>4.16</b> 2 variáveis com VI contínua (e VD contínua)</a></li>
<li class="chapter" data-level="4.17" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#outros-gráficos-e-configurações"><i class="fa fa-check"></i><b>4.17</b> Outros gráficos e configurações</a></li>
<li class="chapter" data-level="4.18" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#execução-no-jasp"><i class="fa fa-check"></i><b>4.18</b> Execução no JASP</a></li>
<li class="chapter" data-level="4.19" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#tabelas-1"><i class="fa fa-check"></i><b>4.19</b> Tabelas</a></li>
<li class="chapter" data-level="4.20" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#gráficos-2"><i class="fa fa-check"></i><b>4.20</b> Gráficos</a></li>
<li class="chapter" data-level="4.21" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variável-discreta-1"><i class="fa fa-check"></i><b>4.21</b> 1 variável discreta</a></li>
<li class="chapter" data-level="4.22" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variável-contínua-1"><i class="fa fa-check"></i><b>4.22</b> 1 variável contínua</a></li>
<li class="chapter" data-level="4.23" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variáveis-com-vi-discreta-e-vd-contínua-1"><i class="fa fa-check"></i><b>4.23</b> 2 variáveis com VI discreta (e VD contínua)</a></li>
<li class="chapter" data-level="4.24" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variáveis-com-vi-contínua-e-vd-contínua-1"><i class="fa fa-check"></i><b>4.24</b> 2 variáveis com VI contínua (e VD contínua)</a></li>
<li class="chapter" data-level="4.25" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#outros-gráficos-e-configurações-1"><i class="fa fa-check"></i><b>4.25</b> Outros gráficos e configurações</a></li>
<li class="chapter" data-level="4.26" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#resumo-2"><i class="fa fa-check"></i><b>4.26</b> Resumo</a></li>
<li class="chapter" data-level="4.27" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#questões-1"><i class="fa fa-check"></i><b>4.27</b> Questões</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="qui-quadrado.html"><a href="qui-quadrado.html"><i class="fa fa-check"></i><b>5</b> Qui quadrado</a><ul>
<li class="chapter" data-level="5.1" data-path="qui-quadrado.html"><a href="qui-quadrado.html#pesquisa-1"><i class="fa fa-check"></i><b>5.1</b> Pesquisa</a></li>
<li class="chapter" data-level="5.2" data-path="qui-quadrado.html"><a href="qui-quadrado.html#execução-no-r-1"><i class="fa fa-check"></i><b>5.2</b> Execução no R</a></li>
<li class="chapter" data-level="5.3" data-path="qui-quadrado.html"><a href="qui-quadrado.html#tamanho-do-efeito"><i class="fa fa-check"></i><b>5.3</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="5.4" data-path="qui-quadrado.html"><a href="qui-quadrado.html#execução-no-jasp-1"><i class="fa fa-check"></i><b>5.4</b> Execução no JASP</a></li>
<li class="chapter" data-level="5.5" data-path="qui-quadrado.html"><a href="qui-quadrado.html#escrita-dos-resultados"><i class="fa fa-check"></i><b>5.5</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="5.6" data-path="qui-quadrado.html"><a href="qui-quadrado.html#resumo-3"><i class="fa fa-check"></i><b>5.6</b> Resumo</a></li>
<li class="chapter" data-level="5.7" data-path="qui-quadrado.html"><a href="qui-quadrado.html#pesquisas-adicionais"><i class="fa fa-check"></i><b>5.7</b> Pesquisas adicionais</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html"><i class="fa fa-check"></i><b>6</b> Tipos de amostragem</a><ul>
<li class="chapter" data-level="6.1" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#amostragem-aleatória-simples"><i class="fa fa-check"></i><b>6.1</b> Amostragem aleatória simples</a></li>
<li class="chapter" data-level="6.2" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#amostragem-aleatória-sistemática"><i class="fa fa-check"></i><b>6.2</b> Amostragem aleatória sistemática</a></li>
<li class="chapter" data-level="6.3" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#amostragem-estratificada"><i class="fa fa-check"></i><b>6.3</b> Amostragem estratificada</a></li>
<li class="chapter" data-level="6.4" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#amostragem-por-conglomerados"><i class="fa fa-check"></i><b>6.4</b> Amostragem por conglomerados</a></li>
<li class="chapter" data-level="6.5" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#amostragem-por-conveniência"><i class="fa fa-check"></i><b>6.5</b> Amostragem por conveniência</a></li>
<li class="chapter" data-level="6.6" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#amostragem-por-auto-seleção"><i class="fa fa-check"></i><b>6.6</b> Amostragem por auto-seleção</a></li>
<li class="chapter" data-level="6.7" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#amostragem-intencional"><i class="fa fa-check"></i><b>6.7</b> Amostragem intencional</a></li>
<li class="chapter" data-level="6.8" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#amostragem-por-bola-de-neve"><i class="fa fa-check"></i><b>6.8</b> Amostragem por bola de neve</a></li>
<li class="chapter" data-level="6.9" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#amostragem-por-quotas"><i class="fa fa-check"></i><b>6.9</b> Amostragem por quotas</a></li>
<li class="chapter" data-level="6.10" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#o-cálculo-do-tamanho-amostral"><i class="fa fa-check"></i><b>6.10</b> O cálculo do tamanho amostral</a></li>
<li class="chapter" data-level="6.11" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#amostragem-e-sua-relação-com-os-resultados"><i class="fa fa-check"></i><b>6.11</b> Amostragem e sua relação com os resultados</a></li>
<li class="chapter" data-level="6.12" data-path="tipos-de-amostragem.html"><a href="tipos-de-amostragem.html#amostragem-delineamento-e-generalização"><i class="fa fa-check"></i><b>6.12</b> Amostragem, delineamento e generalização</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html"><i class="fa fa-check"></i><b>7</b> Estatística Inferencial</a><ul>
<li class="chapter" data-level="7.1" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html#nhst-teste-de-significância-de-hipótese-nula"><i class="fa fa-check"></i><b>7.1</b> NHST (Teste de Significância de Hipótese Nula)</a><ul>
<li class="chapter" data-level="7.1.1" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html#a-primeira-etapa-a-hipótese"><i class="fa fa-check"></i><b>7.1.1</b> A primeira etapa: a hipótese</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html#nível-de-significância"><i class="fa fa-check"></i><b>7.2</b> Nível de significância</a></li>
<li class="chapter" data-level="7.3" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html#o-teste-estatístico"><i class="fa fa-check"></i><b>7.3</b> O teste estatístico</a></li>
<li class="chapter" data-level="7.4" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html#o-valor-de-p"><i class="fa fa-check"></i><b>7.4</b> O valor de P</a></li>
<li class="chapter" data-level="7.5" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html#o-tamanho-do-efeito"><i class="fa fa-check"></i><b>7.5</b> O tamanho do efeito</a></li>
<li class="chapter" data-level="7.6" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html#um-exemplo-intuitivo"><i class="fa fa-check"></i><b>7.6</b> Um exemplo intuitivo</a></li>
<li class="chapter" data-level="7.7" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html#o-que-não-te-contaram-sobre-inferência-estatística"><i class="fa fa-check"></i><b>7.7</b> O que não te contaram sobre inferência estatística</a></li>
<li class="chapter" data-level="7.8" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html#questões-2"><i class="fa fa-check"></i><b>7.8</b> Questões</a></li>
<li class="chapter" data-level="7.9" data-path="estatística-inferencial.html"><a href="estatística-inferencial.html#pesquisas-adicionais-1"><i class="fa fa-check"></i><b>7.9</b> Pesquisas adicionais</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="teste-t.html"><a href="teste-t.html"><i class="fa fa-check"></i><b>8</b> Teste T</a><ul>
<li class="chapter" data-level="8.1" data-path="teste-t.html"><a href="teste-t.html#pesquisa-2"><i class="fa fa-check"></i><b>8.1</b> Pesquisa</a></li>
<li class="chapter" data-level="8.2" data-path="teste-t.html"><a href="teste-t.html#execução-no-r-2"><i class="fa fa-check"></i><b>8.2</b> Execução no R</a></li>
<li class="chapter" data-level="8.3" data-path="teste-t.html"><a href="teste-t.html#tamanho-do-efeito-1"><i class="fa fa-check"></i><b>8.3</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="8.4" data-path="teste-t.html"><a href="teste-t.html#execução-no-jasp-2"><i class="fa fa-check"></i><b>8.4</b> Execução no JASP</a></li>
<li class="chapter" data-level="8.5" data-path="teste-t.html"><a href="teste-t.html#escrita-dos-resultados-1"><i class="fa fa-check"></i><b>8.5</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="8.6" data-path="teste-t.html"><a href="teste-t.html#versão-robusta-do-teste-t"><i class="fa fa-check"></i><b>8.6</b> Versão robusta do Teste T</a><ul>
<li class="chapter" data-level="8.6.1" data-path="teste-t.html"><a href="teste-t.html#execução-no-r-3"><i class="fa fa-check"></i><b>8.6.1</b> Execução no R</a></li>
<li class="chapter" data-level="8.6.2" data-path="teste-t.html"><a href="teste-t.html#execução-no-jasp-3"><i class="fa fa-check"></i><b>8.6.2</b> Execução no JASP</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="teste-t.html"><a href="teste-t.html#mann-whitney"><i class="fa fa-check"></i><b>8.7</b> Mann-whitney</a><ul>
<li class="chapter" data-level="8.7.1" data-path="teste-t.html"><a href="teste-t.html#execução-no-r-4"><i class="fa fa-check"></i><b>8.7.1</b> Execução No R</a></li>
<li class="chapter" data-level="8.7.2" data-path="teste-t.html"><a href="teste-t.html#tamanho-do-efeito-2"><i class="fa fa-check"></i><b>8.7.2</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="8.7.3" data-path="teste-t.html"><a href="teste-t.html#execução-no-jasp-4"><i class="fa fa-check"></i><b>8.7.3</b> Execução no JASP</a></li>
<li class="chapter" data-level="8.7.4" data-path="teste-t.html"><a href="teste-t.html#escrita-dos-resultados-2"><i class="fa fa-check"></i><b>8.7.4</b> Escrita dos resultados</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="teste-t.html"><a href="teste-t.html#teste-t-e-regressão"><i class="fa fa-check"></i><b>8.8</b> Teste T e regressão</a></li>
<li class="chapter" data-level="8.9" data-path="teste-t.html"><a href="teste-t.html#resumo-4"><i class="fa fa-check"></i><b>8.9</b> Resumo</a></li>
<li class="chapter" data-level="8.10" data-path="teste-t.html"><a href="teste-t.html#pesquisas-adicionais-2"><i class="fa fa-check"></i><b>8.10</b> Pesquisas adicionais</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>9</b> ANOVA</a><ul>
<li class="chapter" data-level="9.1" data-path="anova.html"><a href="anova.html#glossário"><i class="fa fa-check"></i><b>9.1</b> Glossário</a></li>
<li class="chapter" data-level="9.2" data-path="anova.html"><a href="anova.html#pesquisa-3"><i class="fa fa-check"></i><b>9.2</b> Pesquisa</a></li>
<li class="chapter" data-level="9.3" data-path="anova.html"><a href="anova.html#anova-de-1-via"><i class="fa fa-check"></i><b>9.3</b> ANOVA de 1 via</a></li>
<li class="chapter" data-level="9.4" data-path="anova.html"><a href="anova.html#execução-no-r-5"><i class="fa fa-check"></i><b>9.4</b> Execução no R</a></li>
<li class="chapter" data-level="9.5" data-path="anova.html"><a href="anova.html#tamanho-do-efeito-3"><i class="fa fa-check"></i><b>9.5</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="9.6" data-path="anova.html"><a href="anova.html#execução-no-jasp-5"><i class="fa fa-check"></i><b>9.6</b> Execução no JASP</a></li>
<li class="chapter" data-level="9.7" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-3"><i class="fa fa-check"></i><b>9.7</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="9.8" data-path="anova.html"><a href="anova.html#post-hoc"><i class="fa fa-check"></i><b>9.8</b> Post hoc</a></li>
<li class="chapter" data-level="9.9" data-path="anova.html"><a href="anova.html#execução-no-r-6"><i class="fa fa-check"></i><b>9.9</b> Execução no R</a></li>
<li class="chapter" data-level="9.10" data-path="anova.html"><a href="anova.html#execução-no-jasp-6"><i class="fa fa-check"></i><b>9.10</b> Execução no JASP</a></li>
<li class="chapter" data-level="9.11" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-4"><i class="fa fa-check"></i><b>9.11</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="9.12" data-path="anova.html"><a href="anova.html#resumo-5"><i class="fa fa-check"></i><b>9.12</b> Resumo</a></li>
<li class="chapter" data-level="9.13" data-path="anova.html"><a href="anova.html#pesquisas-adicionais-3"><i class="fa fa-check"></i><b>9.13</b> Pesquisas adicionais</a></li>
<li class="chapter" data-level="9.14" data-path="anova.html"><a href="anova.html#pesquisa-4"><i class="fa fa-check"></i><b>9.14</b> Pesquisa</a></li>
<li class="chapter" data-level="9.15" data-path="anova.html"><a href="anova.html#anova-de-2-vias"><i class="fa fa-check"></i><b>9.15</b> ANOVA de 2 vias</a></li>
<li class="chapter" data-level="9.16" data-path="anova.html"><a href="anova.html#execução-no-r-7"><i class="fa fa-check"></i><b>9.16</b> Execução no R</a></li>
<li class="chapter" data-level="9.17" data-path="anova.html"><a href="anova.html#execução-no-jasp-7"><i class="fa fa-check"></i><b>9.17</b> Execução no JASP</a></li>
<li class="chapter" data-level="9.18" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-5"><i class="fa fa-check"></i><b>9.18</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="9.19" data-path="anova.html"><a href="anova.html#post-hoc-1"><i class="fa fa-check"></i><b>9.19</b> Post hoc</a></li>
<li class="chapter" data-level="9.20" data-path="anova.html"><a href="anova.html#execução-no-r-8"><i class="fa fa-check"></i><b>9.20</b> Execução no R</a></li>
<li class="chapter" data-level="9.21" data-path="anova.html"><a href="anova.html#execução-no-jasp-8"><i class="fa fa-check"></i><b>9.21</b> Execução no JASP</a></li>
<li class="chapter" data-level="9.22" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-6"><i class="fa fa-check"></i><b>9.22</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="9.23" data-path="anova.html"><a href="anova.html#resumo-6"><i class="fa fa-check"></i><b>9.23</b> Resumo</a></li>
<li class="chapter" data-level="9.24" data-path="anova.html"><a href="anova.html#anova-fatorial"><i class="fa fa-check"></i><b>9.24</b> ANOVA Fatorial</a></li>
<li class="chapter" data-level="9.25" data-path="anova.html"><a href="anova.html#execução-no-r-9"><i class="fa fa-check"></i><b>9.25</b> Execução no R</a></li>
<li class="chapter" data-level="9.26" data-path="anova.html"><a href="anova.html#execução-no-jasp-9"><i class="fa fa-check"></i><b>9.26</b> Execução no JASP</a></li>
<li class="chapter" data-level="9.27" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-7"><i class="fa fa-check"></i><b>9.27</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="9.28" data-path="anova.html"><a href="anova.html#resumo-7"><i class="fa fa-check"></i><b>9.28</b> Resumo</a></li>
<li class="chapter" data-level="9.29" data-path="anova.html"><a href="anova.html#post-hoc-2"><i class="fa fa-check"></i><b>9.29</b> Post hoc</a></li>
<li class="chapter" data-level="9.30" data-path="anova.html"><a href="anova.html#execução-no-jasp-10"><i class="fa fa-check"></i><b>9.30</b> Execução no JASP</a></li>
<li class="chapter" data-level="9.31" data-path="anova.html"><a href="anova.html#escrita-dos-resultados-8"><i class="fa fa-check"></i><b>9.31</b> Escrita dos resultados</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html"><i class="fa fa-check"></i><b>10</b> ANOVA de medidas repetidas</a><ul>
<li class="chapter" data-level="10.1" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#pesquisa-5"><i class="fa fa-check"></i><b>10.1</b> Pesquisa</a></li>
<li class="chapter" data-level="10.2" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#execução-no-r-10"><i class="fa fa-check"></i><b>10.2</b> Execução no R</a></li>
<li class="chapter" data-level="10.3" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#tamanho-do-efeito-4"><i class="fa fa-check"></i><b>10.3</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="10.4" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#execução-no-jasp-11"><i class="fa fa-check"></i><b>10.4</b> Execução no JASP</a></li>
<li class="chapter" data-level="10.5" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#escrita-dos-resultados-9"><i class="fa fa-check"></i><b>10.5</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="10.6" data-path="anova-de-medidas-repetidas.html"><a href="anova-de-medidas-repetidas.html#resumo-8"><i class="fa fa-check"></i><b>10.6</b> Resumo</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="modelo-linear-misto.html"><a href="modelo-linear-misto.html"><i class="fa fa-check"></i><b>11</b> Modelo linear misto</a><ul>
<li class="chapter" data-level="11.1" data-path="modelo-linear-misto.html"><a href="modelo-linear-misto.html#pesquisa-6"><i class="fa fa-check"></i><b>11.1</b> Pesquisa</a></li>
<li class="chapter" data-level="11.2" data-path="modelo-linear-misto.html"><a href="modelo-linear-misto.html#execução-no-r-11"><i class="fa fa-check"></i><b>11.2</b> execução no R</a></li>
<li class="chapter" data-level="11.3" data-path="modelo-linear-misto.html"><a href="modelo-linear-misto.html#execução-no-jasp-12"><i class="fa fa-check"></i><b>11.3</b> Execução no JASP</a></li>
<li class="chapter" data-level="11.4" data-path="modelo-linear-misto.html"><a href="modelo-linear-misto.html#escrita-dos-resultados-10"><i class="fa fa-check"></i><b>11.4</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="11.5" data-path="modelo-linear-misto.html"><a href="modelo-linear-misto.html#resumo-9"><i class="fa fa-check"></i><b>11.5</b> Resumo</a></li>
<li class="chapter" data-level="11.6" data-path="modelo-linear-misto.html"><a href="modelo-linear-misto.html#pesquisas-adicionais-4"><i class="fa fa-check"></i><b>11.6</b> Pesquisas adicionais</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="correlação.html"><a href="correlação.html"><i class="fa fa-check"></i><b>12</b> Correlação</a><ul>
<li class="chapter" data-level="12.1" data-path="correlação.html"><a href="correlação.html#pesquisa-7"><i class="fa fa-check"></i><b>12.1</b> Pesquisa</a></li>
<li class="chapter" data-level="12.2" data-path="correlação.html"><a href="correlação.html#execução-no-r-12"><i class="fa fa-check"></i><b>12.2</b> Execução no R</a></li>
<li class="chapter" data-level="12.3" data-path="correlação.html"><a href="correlação.html#execução-no-jasp-13"><i class="fa fa-check"></i><b>12.3</b> Execução no JASP</a></li>
<li class="chapter" data-level="12.4" data-path="correlação.html"><a href="correlação.html#escrita-dos-resultados-11"><i class="fa fa-check"></i><b>12.4</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="12.5" data-path="correlação.html"><a href="correlação.html#resumo-10"><i class="fa fa-check"></i><b>12.5</b> Resumo</a></li>
<li class="chapter" data-level="12.6" data-path="correlação.html"><a href="correlação.html#pesquisas-adicionais-5"><i class="fa fa-check"></i><b>12.6</b> Pesquisas adicionais</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html"><i class="fa fa-check"></i><b>13</b> Regressão linear simples</a><ul>
<li class="chapter" data-level="13.1" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#glossário-1"><i class="fa fa-check"></i><b>13.1</b> Glossário</a></li>
<li class="chapter" data-level="13.2" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#breve-explicação-conceitual"><i class="fa fa-check"></i><b>13.2</b> Breve explicação conceitual</a></li>
<li class="chapter" data-level="13.3" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#pesquisa-8"><i class="fa fa-check"></i><b>13.3</b> Pesquisa</a></li>
<li class="chapter" data-level="13.4" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#execução-no-r-13"><i class="fa fa-check"></i><b>13.4</b> Execução no R</a></li>
<li class="chapter" data-level="13.5" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#execução-no-jasp-14"><i class="fa fa-check"></i><b>13.5</b> Execução no JASP</a></li>
<li class="chapter" data-level="13.6" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#escrita-dos-resultados-12"><i class="fa fa-check"></i><b>13.6</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="13.7" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#resumo-11"><i class="fa fa-check"></i><b>13.7</b> Resumo</a></li>
<li class="chapter" data-level="13.8" data-path="regressão-linear-simples.html"><a href="regressão-linear-simples.html#pesquisas-adicionais-6"><i class="fa fa-check"></i><b>13.8</b> Pesquisas adicionais</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html"><i class="fa fa-check"></i><b>14</b> Regressão linear múltipla</a><ul>
<li class="chapter" data-level="14.1" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#pesquisa-9"><i class="fa fa-check"></i><b>14.1</b> Pesquisa</a></li>
<li class="chapter" data-level="14.2" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#execução-no-r-14"><i class="fa fa-check"></i><b>14.2</b> Execução no R</a></li>
<li class="chapter" data-level="14.3" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#execução-no-jasp-15"><i class="fa fa-check"></i><b>14.3</b> Execução no JASP</a></li>
<li class="chapter" data-level="14.4" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#escrita-dos-resultados-13"><i class="fa fa-check"></i><b>14.4</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="14.5" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#técnicas-automáticas-de-seleção-de-variáveis"><i class="fa fa-check"></i><b>14.5</b> Técnicas automáticas de seleção de variáveis</a></li>
<li class="chapter" data-level="14.6" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#resumo-12"><i class="fa fa-check"></i><b>14.6</b> Resumo</a></li>
<li class="chapter" data-level="14.7" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#pesquisas-adicionais-7"><i class="fa fa-check"></i><b>14.7</b> Pesquisas adicionais</a></li>
<li class="chapter" data-level="14.8" data-path="regressão-linear-múltipla.html"><a href="regressão-linear-múltipla.html#questões-3"><i class="fa fa-check"></i><b>14.8</b> Questões</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="regressão-logística-binária.html"><a href="regressão-logística-binária.html"><i class="fa fa-check"></i><b>15</b> Regressão logística binária</a><ul>
<li class="chapter" data-level="15.1" data-path="regressão-logística-binária.html"><a href="regressão-logística-binária.html#pesquisa-10"><i class="fa fa-check"></i><b>15.1</b> Pesquisa</a></li>
<li class="chapter" data-level="15.2" data-path="regressão-logística-binária.html"><a href="regressão-logística-binária.html#execução-no-r-15"><i class="fa fa-check"></i><b>15.2</b> Execução no R</a></li>
<li class="chapter" data-level="15.3" data-path="regressão-logística-binária.html"><a href="regressão-logística-binária.html#execução-no-jasp-16"><i class="fa fa-check"></i><b>15.3</b> Execução no JASP</a></li>
<li class="chapter" data-level="15.4" data-path="regressão-logística-binária.html"><a href="regressão-logística-binária.html#escrita-dos-resultados-14"><i class="fa fa-check"></i><b>15.4</b> Escrita dos resultados</a></li>
<li class="chapter" data-level="15.5" data-path="regressão-logística-binária.html"><a href="regressão-logística-binária.html#regressão-logística-e-qui-quadrado"><i class="fa fa-check"></i><b>15.5</b> Regressão logística e Qui-quadrado</a></li>
<li class="chapter" data-level="15.6" data-path="regressão-logística-binária.html"><a href="regressão-logística-binária.html#resumo-13"><i class="fa fa-check"></i><b>15.6</b> Resumo</a></li>
<li class="chapter" data-level="15.7" data-path="regressão-logística-binária.html"><a href="regressão-logística-binária.html#pesquisas-adicionais-8"><i class="fa fa-check"></i><b>15.7</b> Pesquisas adicionais</a></li>
<li class="chapter" data-level="15.8" data-path="regressão-logística-binária.html"><a href="regressão-logística-binária.html#questões-4"><i class="fa fa-check"></i><b>15.8</b> Questões</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="http://www.puc-rio.br/" target="blank">PUC-Rio</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Métodos quantitativos em Psicologia com R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regressão-logística-binária" class="section level1">
<h1><span class="header-section-number">Cap. 15</span> Regressão logística binária</h1>
<div class="writing">
<p>
<strong>GLOSSÁRIO</strong>
</p>
<p>
<strong>Modelo Linear Generalizado</strong>: Classe de modelos compostos por uma função de ligação, preditores lineares e uma distribuição de probabilidades. São ampliações de modelos lineares.<br />
<strong>Função de ligação</strong>: Termo que associa os valores esperados da resposta aos preditores lineares no modelo.<br />
<strong>Logit</strong>: Uma função de ligação que transforma probabilidades em chances.<br />
<strong>Risco</strong>: Probabilidade ou proporção.<br />
<strong>Chance ou Odds</strong>: Caso particular de uma razão em que o numerador não está contido no denominador. Tradução para Odds.<br />
<strong>Razão de Chances ou Odds Ratio</strong>: Medida de tamanho de efeito que indica a chance de ocorrência de um desfecho em um grupo quando comparado a outro. Seus valores variam entre 0 e infinito.
</p>
</div>
<p>A regressão logística é um modelo estatístico que permite estimar a chance da ocorrência de um determinado desfecho categórico (Y) em função de um ou mais preditores (X), que podem ser contínuos ou categóricos. Quando a variável dependente apresenta apenas dois níveis ou classes, a regressão é chamada de binária. Quando há mais níveis ou classes, é chamada de multinomial.</p>
<p>Assim, é possível entender a regressão logística como um complemento da regressão linear aplicada a variáveis categóricas a partir de uma função de ligação ou, de maneira geral, um caso particular da famiília dos modelos lineares generalizados (GLM), que implementa uma ligação logit.</p>
<p>Conceitualmente, neste modelo há os seguintes termos:</p>
<p><span class="math display">\[\underbrace{ln\left ( \frac{P}{1-P} \right)}_\text{logit} = b_0+b_1X_1+ \dots + b_iX_i\]</span></p>
<p>Onde:<br />
<span class="math inline">\(P\)</span> representa a probabilidade de um desfecho ocorrer<br />
<span class="math inline">\(1-P\)</span> representa a probabilidade de um desfecho não ocorrer<br />
<span class="math inline">\(ln\left ( \frac{P}{1-P} \right)\)</span> representa uma transformação logit variável dependente<br />
<span class="math inline">\(b_0\)</span> é o intercepto<br />
<span class="math inline">\(b_i\)</span> indica os preditores</p>
<p>Os seguintes pressupostos devem ser investigados:</p>
<p><em>(i)</em> Os dados são aleatórios e representativos da população<br />
<em>(ii)</em> A variável dependente é dicotômica/binária<br />
<em>(iii)</em> Os preditores não apresentam alta correlação<br />
<em>(iv)</em> Há uma relação linear entre preditores contínuos e o logit do desfecho</p>
<p>Há muitas aplicações de modelos logísticos. Em áreas de saúde, eles tendem a ser os modelos de primeira escolha para verificar possíveis condições clínicas e de agravo à saúde. Em Psicologia, por exemplo, ele é util para descrever e investigar os possíveis preditores de condições diagnósticas bem definidas, tal como TDAH e outros transtornos psiquiátricos. Em epidemiologia, eles são fundamentais em estudos do tipo caso-controle.</p>
<p>Algumas condições são importantes:<br />
(1) A variável dependente nesta equação é um transformação logit da probabilidade da presença de um determinado desfecho. Ela não é, por definição, uma probabilidade, mas sim uma função.<br />
(2) Não há a definção de um termo de erro (tal como nos modelos de regressão linear) e<br />
(3) o desfecho é assumido seguir uma distribuição binomial.</p>
<p>Como exposto, os resultados da regressão logística informam sobre <u>chances</u> (<em>Odds</em>) e <u>Razão de chances</u> (<em>Odds Ratio</em>) e não sobre probabilidades, diretamente. Existem muitas formas de demonstrar esta diferença. Entretanto, julgo que a forma mais simples é ilustrá-la matematicamente.</p>
<p>Uma probabilidade é uma razão entre uma parte contra o todo (<em>Tudo o que tenho sobre tudo o que posso quero</em>, em jargão pedagógico). A chance é uma razão em que o numerador é uma probabilidade e o denominador é seu complemento. A figura a seguir ilustra essa diferença.<br />
<img src="img/cap_reg_log_odds.PNG" /></p>
<p>É legítimo ter dificuldade na interpretação do conceito, além de questionar o motivo pelo qual ele é tão utilizado nestas áreas. No entanto, uma ajuda interpretativa é lembrar que a probabilidade, maior também serão as chances de um determinado evento. A relação entre ambos tem o seguinte formato.</p>
<p><img src="gitbook-demo_files/figure-html/unnamed-chunk-193-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>A métrica Razão de chances (Odds Ratio ou OR) é utilizada como uma medida de tamanho de efeito que se dá pela comparação entre dois grupos.</p>
<p>Como em áreas de saúde, tradicionalmente, o interesse é verificar situações clínicas, quanto maior for o OR, maior será a chance da ocorrência de um desfecho negativo em um determinado grupo em comparação à outra e, consequentemente, maior o risco.</p>
<p>Neste sentido:</p>
<table>
<thead>
<tr class="header">
<th align="left">Chance</th>
<th align="left">Probabilidade</th>
<th align="left">Interpretação</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">&lt; 1</td>
<td align="left">&lt; 50%</td>
<td align="left">Fator de risco</td>
</tr>
<tr class="even">
<td align="left">= 1</td>
<td align="left">50%</td>
<td align="left">Fator neutro</td>
</tr>
<tr class="odd">
<td align="left">&gt; 1</td>
<td align="left">&gt; 50%</td>
<td align="left">Fator de proteção</td>
</tr>
</tbody>
</table>
<div id="pesquisa-10" class="section level2">
<h2><span class="header-section-number">15.1</span> Pesquisa</h2>
<div class="base">
<p>A base desta pesquisa está disponível em formato <strong>R (Rdata)</strong> e em <strong>CSV</strong>, que é lido pelo JASP. Clique na opção desejada.</p>
<p><strong>R Base: </strong> <a href="https://github.com/anovabr/mqt/raw/master/bases/Base%20R%20-%20Headache%20anonymous.RData">Base R - Headache anonymous</a><br />
<strong>Base JASP : </strong> <a href="https://github.com/anovabr/mqt/raw/master/bases/bases_csv_jasp.zip">Base CSV - headache (no names)</a></p>
</div>
<p>Neste capítulo, vamos utilizar a pesquisa intitulada <a href="https://www.researchgate.net/publication/323729370_Aspects_Related_to_Body_Image_and_Eating_Behaviors_in_Healthy_Brazilian_Undergraduate_Students">“Resilience and vulnerability in adolescents with primary headaches: a cross-sectional population-based study”</a>, publicada em 2021 no Headache, que sou coautor.</p>
<p>Essa é uma pesquisa censitária, que contou com todos os 339 estudantes de uma cidade pequena no interior do Brasil. O estudo visou mapear as possíveis condições de baixos recursos psicológicos e alta vulnerabilidade em adolescentes portadores de enxaqueca de diferentes tipos e intensidades. Na literatura médica internacional, são raros os estudos com finalidade epidemiológica descritiva sobre enxaqueca. No Brasil, por sua vez, este nosso estudo foi o primeiro. Esse fato marcou o caráter inovador da pesquisa e também permitiu impactar positivamente o trabalho de clínicos que, em seu dia a dia, lidam com jovens com tais características.</p>
<p>Para definir o tipo e a frequência da dor de cabeça, os participantes responderam a diferentes questionários médicos. Por sua vez, para verificar um possível risco de participantes enxaquecocos apresentarem baixos recursos psicológicos e alta vulnerabilidade, eles foram submetidos à escala <em>Resiliency Scales for Children and Adolescents</em>, que foi desenvolvida justamente para medir tais condições.</p>
<p>Uma dos objetivos que tivemos na execução das análises foi verificar quais eram os preditores significativos que poderiam impactar na probabilidade de um adolescente estar no grupo de risco de vulnerabilidade psicológica. Os preditores de interesse foram a idade da criança (age), sua etnia (race), sexo (sex), classe sócioeconômica (ses), problemas de sono (sleeping), prematuridade (premature), fumo durante a gestão (smoking), uso de álcool durante a gestação (alcohol) e possível TDAH (sdq_risk).</p>
<p>Para isso, modelos de regressão logística binária foram utilizados.</p>
</div>
<div id="execução-no-r-15" class="section level2">
<h2><span class="header-section-number">15.2</span> Execução no R</h2>
<p>A primeira etapa da análise é realizada pelo desenvolvimento de tabelas e gráficos que possam auxiliar na interpretação dos resultados. De maneira similar à feita em outros capítulos, abaixo há uma tabela descritiva.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="regressão-logística-binária.html#cb168-1"></a>arsenal<span class="op">::</span><span class="kw">tableby</span>(risk_cefaleia_resources <span class="op">~</span><span class="st"> </span></span>
<span id="cb168-2"><a href="regressão-logística-binária.html#cb168-2"></a><span class="st">                   </span>age <span class="op">+</span><span class="st"> </span>race <span class="op">+</span><span class="st">  </span>sex <span class="op">+</span><span class="st"> </span>ses <span class="op">+</span><span class="st"> </span>sleeping <span class="op">+</span><span class="st"> </span>premature <span class="op">+</span><span class="st"> </span>smoking <span class="op">+</span><span class="st"> </span>alcohol <span class="op">+</span><span class="st"> </span>sdq_risk, </span>
<span id="cb168-3"><a href="regressão-logística-binária.html#cb168-3"></a>                 base_uso) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>() </span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="center">0 (N=312)</th>
<th align="center">1 (N=27)</th>
<th align="center">Total (N=339)</th>
<th align="right">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><strong>age</strong></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="right">0.179</td>
</tr>
<tr class="even">
<td align="left">   Mean (SD)</td>
<td align="center">13.929 (2.068)</td>
<td align="center">13.370 (2.060)</td>
<td align="center">13.885 (2.070)</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">   Range</td>
<td align="center">10.000 - 18.000</td>
<td align="center">11.000 - 18.000</td>
<td align="center">10.000 - 18.000</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left"><strong>race</strong></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="right">0.782</td>
</tr>
<tr class="odd">
<td align="left">   N-Miss</td>
<td align="center">10</td>
<td align="center">0</td>
<td align="center">10</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">   white</td>
<td align="center">220 (72.8%)</td>
<td align="center">19 (70.4%)</td>
<td align="center">239 (72.6%)</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">   Other</td>
<td align="center">82 (27.2%)</td>
<td align="center">8 (29.6%)</td>
<td align="center">90 (27.4%)</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left"><strong>sex</strong></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="right">0.065</td>
</tr>
<tr class="odd">
<td align="left">   Male</td>
<td align="center">150 (48.1%)</td>
<td align="center">8 (29.6%)</td>
<td align="center">158 (46.6%)</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">   Female</td>
<td align="center">162 (51.9%)</td>
<td align="center">19 (70.4%)</td>
<td align="center">181 (53.4%)</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left"><strong>ses</strong></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="right">0.507</td>
</tr>
<tr class="even">
<td align="left">   AB</td>
<td align="center">83 (26.6%)</td>
<td align="center">10 (37.0%)</td>
<td align="center">93 (27.4%)</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">   C</td>
<td align="center">189 (60.6%)</td>
<td align="center">14 (51.9%)</td>
<td align="center">203 (59.9%)</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">   DE</td>
<td align="center">40 (12.8%)</td>
<td align="center">3 (11.1%)</td>
<td align="center">43 (12.7%)</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left"><strong>sleeping</strong></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="right">0.215</td>
</tr>
<tr class="even">
<td align="left">   N-Miss</td>
<td align="center">7</td>
<td align="center">0</td>
<td align="center">7</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">   no</td>
<td align="center">296 (97.0%)</td>
<td align="center">25 (92.6%)</td>
<td align="center">321 (96.7%)</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">   yes</td>
<td align="center">9 (3.0%)</td>
<td align="center">2 (7.4%)</td>
<td align="center">11 (3.3%)</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left"><strong>premature</strong></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="right">0.524</td>
</tr>
<tr class="even">
<td align="left">   N-Miss</td>
<td align="center">4</td>
<td align="center">2</td>
<td align="center">6</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">   no</td>
<td align="center">272 (88.3%)</td>
<td align="center">21 (84.0%)</td>
<td align="center">293 (88.0%)</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">   yes</td>
<td align="center">36 (11.7%)</td>
<td align="center">4 (16.0%)</td>
<td align="center">40 (12.0%)</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left"><strong>smoking</strong></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="right">0.886</td>
</tr>
<tr class="even">
<td align="left">   N-Miss</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">2</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">   no</td>
<td align="center">243 (78.1%)</td>
<td align="center">20 (76.9%)</td>
<td align="center">263 (78.0%)</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">   yes</td>
<td align="center">68 (21.9%)</td>
<td align="center">6 (23.1%)</td>
<td align="center">74 (22.0%)</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left"><strong>alcohol</strong></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="right">0.845</td>
</tr>
<tr class="even">
<td align="left">   N-Miss</td>
<td align="center">2</td>
<td align="center">1</td>
<td align="center">3</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">   no</td>
<td align="center">278 (89.7%)</td>
<td align="center">23 (88.5%)</td>
<td align="center">301 (89.6%)</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">   yes</td>
<td align="center">32 (10.3%)</td>
<td align="center">3 (11.5%)</td>
<td align="center">35 (10.4%)</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left"><strong>sdq_risk</strong></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="right">&lt; 0.001</td>
</tr>
<tr class="even">
<td align="left">   no</td>
<td align="center">287 (92.0%)</td>
<td align="center">19 (70.4%)</td>
<td align="center">306 (90.3%)</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">   yes</td>
<td align="center">25 (8.0%)</td>
<td align="center">8 (29.6%)</td>
<td align="center">33 (9.7%)</td>
<td align="right"></td>
</tr>
</tbody>
</table>
<p>Essa tabela oferece uma primeira informação sobre os dados e poderia ser utilizada também para computar vários testes Qui-quadrado. Entretanto, o qui-quadrado serviria para verificar relacionamentos bivariados, mas não controlaria os resultados pelas outras variáveis de interesse. Apesar de ser possível fazer alguns ajustes particulares ou utilizar o teste de Cochran–Mantel–Haenszel, a regressão logística é a modelagem mais adaptada para lidar com esta situação.</p>
<p>Para executar esse tipo de regressão no R, será necessário usar a função nativa <code>glm</code> e deixar claro que a família é a <code>binomial</code>. Isso indicará que o desfecho é binário e que a função logit deverá ser implementada na equação.</p>
<p>O vetor <code>mod_risco</code> será criado e reunirá os resultados do modelo de regressão logística.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="regressão-logística-binária.html#cb169-1"></a>mod_risco &lt;-<span class="st"> </span><span class="kw">glm</span>(risk_cefaleia_resources <span class="op">~</span></span>
<span id="cb169-2"><a href="regressão-logística-binária.html#cb169-2"></a><span class="st">                       </span>age <span class="op">+</span><span class="st"> </span>race <span class="op">+</span><span class="st">  </span>sex <span class="op">+</span><span class="st"> </span>ses <span class="op">+</span><span class="st"> </span>sleeping <span class="op">+</span><span class="st"> </span>premature <span class="op">+</span><span class="st"> </span>smoking <span class="op">+</span><span class="st"> </span>alcohol <span class="op">+</span><span class="st"> </span>sdq_risk, </span>
<span id="cb169-3"><a href="regressão-logística-binária.html#cb169-3"></a>                    <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="dt">data =</span> base_uso)</span></code></pre></div>
<p>Há muitas formas de apresentar os resultados e o pacote <code>sjPlot</code> tem ótimas funções para isso. A tabela produzida gera o Odds Ratio de cada preditor, seu intervalo de confiança, a estatística de teste e o valor de P. Ao fim da tabela, a quantidade de observações utilizada e uma medida de ajuste (<span class="math inline">\(R^2\)</span>) é apresentada.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="regressão-logística-binária.html#cb170-1"></a>sjPlot<span class="op">::</span><span class="kw">tab_model</span>(mod_risco,<span class="dt">show.stat =</span> <span class="ot">TRUE</span>, </span>
<span id="cb170-2"><a href="regressão-logística-binária.html#cb170-2"></a>          <span class="dt">digits =</span> <span class="dv">2</span>)</span></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="4" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
risk cefaleia resources
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Odds Ratios
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Statistic
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2.51
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.08 – 86.90
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.52
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.605
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
age
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.82
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.64 – 1.03
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.63
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.104
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
race1
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.07
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.60 – 1.78
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.23
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.817
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
sex1
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.75
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.08 – 3.06
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2.15
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.032</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
ses1
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.71
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.42 – 1.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.29
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.197
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
ses2
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.98
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.58 – 1.51
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.08
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.938
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
sleeping1
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.09
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.36 – 2.66
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.17
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.868
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
premature1
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.26
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.64 – 2.23
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.75
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.456
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
smoking1
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.94
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.47 – 1.71
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.840
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
alcohol1
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.98
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.43 – 1.94
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.06
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.951
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
sdq_risk1
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2.74
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.59 – 4.73
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
3.67
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="4">
314
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> Tjur
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="4">
0.101
</td>
</tr>
</table>
<p>Essa apresentação não verifica se o modelo testado é mais informativo do que um modelo nulo, mas apenas assume esta condição. Testá-la é particularmente importante em modelos com menos variáveis e isso pode ser feito pela função nativa <code>Summary</code>.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="regressão-logística-binária.html#cb171-1"></a><span class="co">#deviance do modelo nulo</span></span>
<span id="cb171-2"><a href="regressão-logística-binária.html#cb171-2"></a>base_uso <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb171-3"><a href="regressão-logística-binária.html#cb171-3"></a><span class="st">  </span><span class="kw">filter</span>(<span class="kw">across</span>(<span class="kw">c</span>(age,race,sex,ses,sleeping,premature,smoking,alcohol,sdq_risk), <span class="op">~!</span><span class="kw">is.na</span>(.x))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb171-4"><a href="regressão-logística-binária.html#cb171-4"></a><span class="st">  </span><span class="kw">glm</span>(risk_cefaleia_resources <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="dt">data =</span> .) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</span>
<span id="cb171-5"><a href="regressão-logística-binária.html#cb171-5"></a></span>
<span id="cb171-6"><a href="regressão-logística-binária.html#cb171-6"></a><span class="co">#deviance do modelo testado</span></span>
<span id="cb171-7"><a href="regressão-logística-binária.html#cb171-7"></a>mod_risco <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</span></code></pre></div>
<p>Nesta tabela, a primeira interpretação a ser feita é relacionada ao <span class="math inline">\(R^2\)</span>, que está localizado na parte inferior. Existem diferentes maneiras de calculá-lo e sua interpretação não é igual à feita na regressão linear. Enquanto na regressão linear, o <span class="math inline">\(R^2\)</span> se refere à proporção da variância explicada, em modelos logísticos, no geral, o <span class="math inline">\(R^2\)</span> indica o quanto o modelo testado é próximo de um modelo com ajuste perfeito aos dados (saturado) <span class="citation">(Portugues, <a href="#ref-portugues2020" role="doc-biblioref">2020</a>)</span>.</p>
<p>O <span class="math inline">\(R^2 \, de \, Tjur\)</span> é a medida utilizada nesta apresentação e seus valores variam entre 0 e 1. Ele é feito verificando a diferença entre os dados e os valores previstos pelo modelo testado. Quão maior o valor, mais discriminativo é o modelo testado. Neste caso, o o <span class="math inline">\(R^2 \, de \, Tjur\)</span> foi de 0.10.</p>
<p>A segunda interpretação é baseada nos Odds Ratio (OR) e sugere alguma com atenção: o OR indica a <u>chance</u> de ocorrência de um desfecho caso o preditor analisado tenha ocorrido, em comparação com sua não ocorrência. Ele não indica diretamente sobre a probabilidade, apesar disso ser possível de ser feito.</p>
<p>Os preditores <u>sex[female]</u> e <u>sqd_risk</u> foram significativos. A interpretação pode ser feita da seguinte maneira:</p>
<ul>
<li>A chance do participante vir a apresentar baixo recurso psicológico é 3.07 maior em meninas do que em meninos.</li>
<li>A chance do participante vir a apresentar baixo recursos psicológico é 7.53 maior em participantes com TDAH do que em participantes sem TDAH..</li>
</ul>
<p>Eventualmente, variáveis contínuas também podem ser significativas. Caso a variável <u>age</u> tivesse sido significativa, sua interpretação poderia ser:</p>
<ul>
<li>O aumento de 1 ano de idade impacta a chance de vir a apresentar baixos recursos psicológicos em 0.82, indicando uma característica protetiva.</li>
</ul>
<p>A apresentação desses resultados é muito beneficada por gráficos e o <em>Forest plot</em> pode ser utilizado. Neste gráfico, o eixo horizontal apresenta os valores possíveis de OR (<span class="math inline">\(0-\infty\)</span>) e o eixo vertical todos os preditores analisados. A interpretação é feita em contraste ao valor 1, que está ao centro e indica que os resultados não são distintos entre os grupos ou níveis da variáveis. Valores de OR acima de 1 se situam à direita e indicam um possível fator de risco. Valores de OR abaixo de 1 se situam à esquerda e indicam um possível fator protetivo.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="regressão-logística-binária.html#cb172-1"></a>sjPlot<span class="op">::</span><span class="kw">plot_model</span>(mod_risco,</span>
<span id="cb172-2"><a href="regressão-logística-binária.html#cb172-2"></a>            <span class="dt">grid =</span> <span class="ot">FALSE</span>, </span>
<span id="cb172-3"><a href="regressão-logística-binária.html#cb172-3"></a>            <span class="dt">show.values =</span> <span class="ot">TRUE</span>, <span class="dt">value.offset =</span> <span class="fl">.3</span>, </span>
<span id="cb172-4"><a href="regressão-logística-binária.html#cb172-4"></a>            <span class="dt">colors =</span> <span class="st">&quot;bw&quot;</span>,</span>
<span id="cb172-5"><a href="regressão-logística-binária.html#cb172-5"></a>            <span class="dt">vline.color =</span> <span class="st">&quot;darkgray&quot;</span>) <span class="op">+</span></span>
<span id="cb172-6"><a href="regressão-logística-binária.html#cb172-6"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">labels =</span> <span class="cf">function</span>(x) <span class="kw">str_wrap</span>(x, <span class="dt">width =</span> <span class="dv">10</span>)) <span class="op">+</span></span>
<span id="cb172-7"><a href="regressão-logística-binária.html#cb172-7"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb172-8"><a href="regressão-logística-binária.html#cb172-8"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;top&quot;</span>)</span></code></pre></div>
<p><img src="gitbook-demo_files/figure-html/unnamed-chunk-198-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Caso haja interesse, é também possível computar as probabilidades e adicioná-las à tabela aplicando <span class="math inline">\(Odds/(1+Odds)\)</span>. Ao fazer isso, uma nova informação será apresentada e poderá ter alguma utilidade para interpretar preditores variáveis categóricas. Tradicionalmente, isso não é feito.</p>
<div class="warning">
<p><strong>Atenção</strong>: A validade das inferências dos resultados depende da adequação ou não dos pressupostos dos testes estatísticos. A avaliação destas condições é parte de um procedimento diagnóstico que deve ser sempre feito.</p>
</div>
<p>Um aspecto importante é que a validade da interpretação dos resultados depende dos pressupostos do modelo estatístico. A violação destes pressupostos distorce, limita ou invalida as interpretações teóricas propostas, uma vez que tanto o aumento do erro do tipo 1 (falso positivo), como do tipo 2 (falso negativo) podem ocorrer <span class="citation">(Barker &amp; Shaw, <a href="#ref-Barker2015" role="doc-biblioref">2015</a>; Ernst &amp; Albers, <a href="#ref-Ernst2017" role="doc-biblioref">2017</a>; Lix et al., <a href="#ref-Lix1996" role="doc-biblioref">1996</a>)</span>. Corriqueiramente, testar os pressupostos é uma etapa <u>anterior</u> à própria realização do teste inferencial. Entretanto, <u>pedagogicamente</u> a apresentação deles após a execução do teste parece mais adequada. Assim, eles serão testados a seguir.</p>
<p><mark>Multicolinearidade</mark>. A multicolinearidade pode ser investigada pela análise chamada Variance Inflaction Factor (VIF). Essa análise verifica o quão correlacionados são os preditores e gera um resultado numérico. Valores abaixo de 4 são tipicamente utilizados para indicar que os preditores <u>não</u> são fortemente correlacioandos e, consequentemente, considerar este pressuposto atendido.</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="regressão-logística-binária.html#cb173-1"></a>car<span class="op">::</span><span class="kw">vif</span>(mod_risco) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pander</span>()</span></code></pre></div>
<table style="width:65%;">
<colgroup>
<col width="22%" />
<col width="11%" />
<col width="6%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="center">GVIF</th>
<th align="center">Df</th>
<th align="center">GVIF^(1/(2*Df))</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>age</strong></td>
<td align="center">1.035</td>
<td align="center">1</td>
<td align="center">1.017</td>
</tr>
<tr class="even">
<td align="center"><strong>race</strong></td>
<td align="center">1.112</td>
<td align="center">1</td>
<td align="center">1.055</td>
</tr>
<tr class="odd">
<td align="center"><strong>sex</strong></td>
<td align="center">1.078</td>
<td align="center">1</td>
<td align="center">1.038</td>
</tr>
<tr class="even">
<td align="center"><strong>ses</strong></td>
<td align="center">1.294</td>
<td align="center">2</td>
<td align="center">1.067</td>
</tr>
<tr class="odd">
<td align="center"><strong>sleeping</strong></td>
<td align="center">1.17</td>
<td align="center">1</td>
<td align="center">1.082</td>
</tr>
<tr class="even">
<td align="center"><strong>premature</strong></td>
<td align="center">1.017</td>
<td align="center">1</td>
<td align="center">1.009</td>
</tr>
<tr class="odd">
<td align="center"><strong>smoking</strong></td>
<td align="center">1.365</td>
<td align="center">1</td>
<td align="center">1.168</td>
</tr>
<tr class="even">
<td align="center"><strong>alcohol</strong></td>
<td align="center">1.155</td>
<td align="center">1</td>
<td align="center">1.075</td>
</tr>
<tr class="odd">
<td align="center"><strong>sdq_risk</strong></td>
<td align="center">1.162</td>
<td align="center">1</td>
<td align="center">1.078</td>
</tr>
</tbody>
</table>
<p><mark>Relação linear entre preditores contínuos e o logit</mark>. O pacote <code>sjplot</code> também pode ser utilizado para testar este pressuposto. Não há um teste formal específico para este pressuposto e, com isso, a decisão é baseada na visualização do relacionamento.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="regressão-logística-binária.html#cb174-1"></a>sjPlot<span class="op">::</span><span class="kw">plot_model</span>(mod_risco, <span class="dt">type =</span> <span class="st">&quot;pred&quot;</span>, <span class="dt">terms =</span>  <span class="st">&quot;age&quot;</span>)</span></code></pre></div>
<p><img src="gitbook-demo_files/figure-html/unnamed-chunk-200-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>O gráfico não sugere desvio da linearidade. Com isso, esse pressuposto é considerado mantido.</p>
<p>Após essas análises, é possível interpretar os resultados.</p>
</div>
<div id="execução-no-jasp-16" class="section level2">
<h2><span class="header-section-number">15.3</span> Execução no JASP</h2>
<p>Inicialmente, é necessário carregar a base intitulada “Base CSV - headache (no names)” para o ambiente JASP. Essa base apresenta as variáveis que foram pesquisadas, bem como um conjunto de variáveis auxiliares que serviram para responder a outras perguntas.</p>
<p>Inicialmente, a apresentação de tabelas e gráficos é sempre muito importante e pode ser feito ao clicar na opção <code>Descriptives</code>.</p>
<p><img src="img/cap_logistica_base.PNG" /></p>
<p>Ao clicar nesta opção, a interface do JASP ser próxima à exposta a seguir. É possível eleger as variáveis que irão ser analisadas e as variáveis que irão funcionar como agrupadores.</p>
<p><img src="img/cap_logistica_descriptives.PNG" /></p>
<p>Neste caso, o interesse é agrupar os resultados pelo risco do participante apresentar baixo recurso. Neste sentido, a variável <u>risk_cefaleia_resources</u> deve ser inserido na parte <code>Split</code> e as variáveis <u>age</u>, <u>race</u>, <u>sex</u>, <u>ses</u>, <u>sleeping</u>, <u>premature</u>, <u>smoking</u>, <u>alcohol</u> e <u>sdq_risk</u> deverão ser inseridas em <code>Variables</code>.</p>
<p>Para a apresentação ficar adequada à escala de medida, é necessário marcar a opção <code>Frequency tables (nominal and ordinal variables)</code>.</p>
<p><img src="img/cap_logistica_descriptives2.PNG" /></p>
<p>A tabela apresentada será bastante informativa e pode ser utilizada também para uma apreensão inicial dos dados. Variáveis contínuas serão resumidas por suas médias e desvios-padrão e variáveis categórias serão apresentadas por contagens e proporções.</p>
<p>Gráficos tendem a ser úteis também para verificar o formato da distribuição dos dados. o JASP permite realizá-los clicando em <code>Plots</code>.</p>
<p><img src="img/cap_logistica_plots.PNG" /></p>
<p>Como há variáveis contínuas (<u>age</u>) e variáveis categóricas (<u>sex</u>, etc) o ideal é apresentar tanto boxplots como gráficos de barras. Ao clicar na opção <code>Boxplot</code> e <code>Distribution plots</code>, o JASP irá realizar todos os gráficos e apresentar ao lado direito.</p>
<p><img src="img/cap_logistica_plots2.PNG" /></p>
<p>A análise conjunta da tabela previamente realizada e os gráficos pode ser feitas. Apesar deste procedimento inicial não ser uma etapa fundamental, ele tem sua aplicação em aspectos descritivos da estatística. Com isto feito, é possível fazer a regressão logística.</p>
<p>Para execução da regressão logística, será necessário clicar em <code>Regression</code> e <code>Logistic Regression</code>.</p>
<p><img src="img/cap_logistica_regression.PNG" /></p>
<p>A tela do JASP irá apresentar algumas opções. O local <code>Dependent variables</code> é onde a VD será inserida. Repare que o JASP somente permitirá variáveis nominas ou ordinais neste espaço. <code>Covariates</code> é o local onde as VIs contínuas serão colocadas e <code>Factors</code> é onde as VIs categóricas serão colocadas.</p>
<p><img src="img/cap_logistica_interface.PNG" /></p>
<p>Para realizar o modelo, será necessário levar a <u>risk_cefaleia_resources</u> para <code>Dependent Variable</code>. Em seguida, <u>age</u> para seção <code>Covariates</code> e <u>race</u>, <u>sex</u>, <u>ses</u>, <u>sleeping</u>, <u>premature</u>, <u>smoking</u>, <u>alcohol</u> e <u>sdq_risk</u> para <code>Factors</code>. Ao fazer isso, o JASP irá fazer as principais análises e apresentar os resultados em uma tabela específica, ao lado direito da tela.</p>
<p><img src="img/cap_logistica_resultado_0.PNG" /></p>
<p>É fácil notar que os resultados apresentados são muitos. É recomendado uma ordem específica para interpretá-los.</p>
<p>Em <u>primeiro momento</u>, é importante verificar o ajuste do modelo na seção <code>Model summary</code>, na parte superior dos resultados. O JASP compara o modelo ajustado <code>H1</code> contra um modelo nulo <code>H0</code> em uma métrica de desvio (<em>Deviance</em>) e pelos critérios de informação de Akaike (AIC) e Bayesiano (BIC). De maneira similar à regressão linear, <code>H0</code> indica o modelo mais simples possível (sem preditores) e <code>H1</code> indica o modelo com os preditores que estão sendo testados. Valores de p são usados como critérios de decisão. Os critérios AIC e BIC são medidas de comparação entre modelos que visam balencear a acurácia do modelo e sua parcimônia. O melhor modelo tende a ser o que apresenta o menor valor.</p>
<p>A síntese desses resultados indica que o modelo testado é mais informativo que o modelo nulo, uma vez que o valor de p foi de 0.008 e o AIC do modelo testado foi inferior, apesar do BIC ter sido superior.</p>
<p><img src="img/cap_logistica_resultado_1.PNG" /></p>
<p>O <u>segundo momento</u> consiste na interpretação de uma métrica análoga ao <span class="math inline">\(R^2\)</span> em modelos de regressão. Na seção <code>Model summary</code>, o JASP apresenta algumas opções de uso. Existem debates na literatura sobre qual resultado é o mais indicado e, cada vez mais, o <span class="math inline">\(R^2 \, de \, Tjur\)</span> tem sido escolhido. Essa é uma métrica entre 0 e 1 que é computada verificando as diferenças médias dos resultados obtidos pelo modelos nulo e pelo modelo testado. Independentemente do <span class="math inline">\(R^2\)</span> escolhido, é importante ter claro que os valores do <span class="math inline">\(R^2 {Cox\,\&amp; \,Snell}\)</span> não estão contido no intervalo 0-1, o que gera dificuldade em sua interpretação. No modelo testado, o <span class="math inline">\(R^2 \, de \, Tjur\)</span> foi de 0.101</p>
<p><img src="img/cap_logistica_resultado_2.PNG" /></p>
<p>O <u>terceiro momento</u> é a análise das estimativas obtidas em cada um dos preditores, que aparece na seção <code>Coefficients</code>. No entanto, os valores que o JASP apresentam são o log(odds) dos resultados, cuja interpretação é pouco intuitiva. Antes de interpretar, é necessário adicionar o Odds Ratio à tabela. Para fazer isso, ao lado esquerdo da interface, é necessário clicar em <code>Statistics</code> e, em seguida <code>Odds Ratio</code>.</p>
<p><img src="img/cap_logistica_resultado_3.PNG" /></p>
<p>O Odds Ratio será adicionado à tabela. Agora, cada um dos preditores poderá ser analisado individualmente, com interpretação levando em consideração o Odds Ratio e os valores de P.</p>
<p><img src="img/cap_logistica_resultado_4.PNG" /></p>
<p>A interpretação do Odds Ratio (OR) precisa ser feita com atenção: ele indica a <u>chance</u> de ocorrência de um desfecho caso o preditor analisado tenha ocorrido, em comparação com sua não ocorrência. Eles não indicam diretamente sobre a probabilidade, apesar disso ser possível de ser feito.</p>
<p>Os preditores <u>sex[1 - Mulheres]</u> e <u>sqd_risk</u> foram significativos. A interpretação pode ser feita da seguinte maneira:</p>
<ul>
<li>A chance do participante vir a apresentar baixo recurso psicológico é 3.07 maior em meninas do que em meninos.</li>
<li>A chance do participante vir a apresentar baixo recursos psicológico é 7.53 maior em participantes com TDAH do que em participantes sem TDAH..</li>
</ul>
<p>Eventualmente, variáveis contínuas também podem ser significativas. Caso a variável <u>age</u> tivesse sido significativa, sua interpretação poderia ser:</p>
<ul>
<li>O aumento de 1 ano de idade impacta a chance de vir a apresentar baixos recursos psicológicos em 0.82, indicando uma característica protetiva.</li>
</ul>
<div class="warning">
<p><strong>Atenção</strong>: A validade das inferências dos resultados depende da adequação ou não dos pressupostos dos testes estatísticos. A avaliação destas condições é parte de um procedimento diagnóstico que deve ser sempre feito.</p>
</div>
<p>Uma vez que o modelo já foi realizado, a interpretação dos resultados depende da adequação de seus pressupostos. A violação destes pressupostos distorce, limita ou invalida as interpretações teóricas propostas, uma vez que tanto o aumento do erro do tipo 1 (falso positivo), como do tipo 2 (falso negativo) podem ocorrer <span class="citation">(Barker &amp; Shaw, <a href="#ref-Barker2015" role="doc-biblioref">2015</a>; Ernst &amp; Albers, <a href="#ref-Ernst2017" role="doc-biblioref">2017</a>; Lix et al., <a href="#ref-Lix1996" role="doc-biblioref">1996</a>)</span>. Corriqueiramente, testar os pressupostos é uma etapa <u>anterior</u> à própria realização do teste inferencial. Entretanto, <u>pedagogicamente</u> a apresentação deles após a execução do teste parece mais adequada. Assim, eles serão testados a seguir.</p>
</div>
<div id="escrita-dos-resultados-14" class="section level2">
<h2><span class="header-section-number">15.4</span> Escrita dos resultados</h2>
<p>De uma forma geral, o principal achado do modelo de regressão é que a percepção da imagem corporal é um preditor significativo ao comportamento alimentar. Neste sentido, ao saber informações sobre como uma pessoa percebe o próprio corpo, pode-se estimar condições eventualmente disfuncionar de seu comportamento alimentar. Abaixo uma sugestão de escrita baseada nas recomendações da American Psychological Association (APA).</p>
<div class="writing">
<p>
<strong>Como escrever os resultados</strong>
</p>
<p>
Um modelo de regressão foi calculado para verificar os resultados dos comportamentos alimentares (EAT-26) em função da percepção de imagem corporal (BSQ-34). Os resultados indicaram que cerca de 46% da variância do EAT-26 pode ser atribuída ao BSQ-34 (R2 = 0.456, F(1,218) = 182.88, p &lt; 0.001). Cada ponto a mais no BSQ-34 impacta, em média, em 0.178 no EAT-26 (b = 0.178, p &lt; 0.001).
</p>
</div>
</div>
<div id="regressão-logística-e-qui-quadrado" class="section level2">
<h2><span class="header-section-number">15.5</span> Regressão logística e Qui-quadrado</h2>
<p>Em uma regressão logística binária em que há apenas um preditor categórico com dois grupos, a analise é baseada em tabelas de contingência. A tabela a seguir apresenta a relação entre o sexo do participante e ele(a) estar incluído ou não na categoria de baixos recursos psicológicos.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="regressão-logística-binária.html#cb175-1"></a><span class="kw">library</span>(janitor)</span>
<span id="cb175-2"><a href="regressão-logística-binária.html#cb175-2"></a>base_uso <span class="op">%&gt;%</span></span>
<span id="cb175-3"><a href="regressão-logística-binária.html#cb175-3"></a><span class="st">  </span><span class="kw">tabyl</span>(sex, risk_cefaleia_resources) <span class="op">%&gt;%</span></span>
<span id="cb175-4"><a href="regressão-logística-binária.html#cb175-4"></a><span class="st">  </span><span class="kw">adorn_totals</span>(<span class="kw">c</span>(<span class="st">&quot;row&quot;</span>, <span class="st">&quot;col&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb175-5"><a href="regressão-logística-binária.html#cb175-5"></a><span class="st">  </span><span class="kw">adorn_percentages</span>(<span class="st">&quot;row&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb175-6"><a href="regressão-logística-binária.html#cb175-6"></a><span class="st">  </span><span class="kw">adorn_pct_formatting</span>(<span class="dt">rounding =</span> <span class="st">&quot;half up&quot;</span>, <span class="dt">digits =</span> <span class="dv">0</span>) <span class="op">%&gt;%</span></span>
<span id="cb175-7"><a href="regressão-logística-binária.html#cb175-7"></a><span class="st">  </span><span class="kw">adorn_ns</span>() <span class="op">%&gt;%</span></span>
<span id="cb175-8"><a href="regressão-logística-binária.html#cb175-8"></a><span class="st">  </span><span class="kw">pander</span>()</span></code></pre></div>
<table style="width:62%;">
<colgroup>
<col width="12%" />
<col width="16%" />
<col width="15%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">sex</th>
<th align="center">0</th>
<th align="center">1</th>
<th align="center">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Male</td>
<td align="center">95% (150)</td>
<td align="center">5% (8)</td>
<td align="center">100% (158)</td>
</tr>
<tr class="even">
<td align="center">Female</td>
<td align="center">90% (162)</td>
<td align="center">10% (19)</td>
<td align="center">100% (181)</td>
</tr>
<tr class="odd">
<td align="center">Total</td>
<td align="center">92% (312)</td>
<td align="center">8% (27)</td>
<td align="center">100% (339)</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="regressão-logística-binária.html#cb176-1"></a>(<span class="dv">19</span><span class="op">/</span><span class="dv">162</span>)<span class="op">/</span>(<span class="dv">8</span><span class="op">/</span><span class="dv">150</span>)</span></code></pre></div>
<pre><code>## [1] 2.199074</code></pre>
<p>Caso o Qui-quadrado de independência fosse calculado, seu valor de P indicara que os grupos não são associados, com estatística de teste = 2.697 e valor de P = 0.206.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="regressão-logística-binária.html#cb178-1"></a>base_uso <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb178-2"><a href="regressão-logística-binária.html#cb178-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">risk =</span> <span class="kw">if_else</span>(risk_cefaleia_resources <span class="op">==</span><span class="st"> &quot;0&quot;</span>,<span class="dv">0</span>,<span class="dv">1</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb178-3"><a href="regressão-logística-binária.html#cb178-3"></a><span class="st">  </span>{<span class="kw">chisq.test</span>(.<span class="op">$</span>sex, .<span class="op">$</span>risk)}</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  .$sex and .$risk
## X-squared = 2.6973, df = 1, p-value = 0.1005</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="regressão-logística-binária.html#cb180-1"></a>base_uso <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb180-2"><a href="regressão-logística-binária.html#cb180-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">risk =</span> <span class="kw">if_else</span>(risk_cefaleia_resources <span class="op">==</span><span class="st"> &quot;0&quot;</span>,<span class="dv">0</span>,<span class="dv">1</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co">#nuneric for poisson </span></span>
<span id="cb180-3"><a href="regressão-logística-binária.html#cb180-3"></a><span class="st">  </span><span class="kw">glm</span>(risk <span class="op">~</span><span class="st"> </span>sex, <span class="dt">family =</span> poisson, <span class="dt">data =</span> .) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb180-4"><a href="regressão-logística-binária.html#cb180-4"></a><span class="st">  </span>car<span class="op">::</span><span class="kw">Anova</span>(., <span class="dt">test.statistic=</span><span class="st">&quot;Wald&quot;</span>, <span class="dt">type =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table (Type II tests)
## 
## Response: risk
##     Df  Chisq Pr(&gt;Chisq)  
## sex  1 2.9926    0.08365 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="regressão-logística-binária.html#cb182-1"></a><span class="kw">glm</span>(risk_cefaleia_resources <span class="op">~</span><span class="st"> </span>sex, <span class="dt">family =</span> binomial, <span class="dt">data =</span> base_uso) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb182-2"><a href="regressão-logística-binária.html#cb182-2"></a><span class="st">  </span>car<span class="op">::</span><span class="kw">Anova</span>(., <span class="dt">test =</span> <span class="st">&quot;Wald&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table (Type II tests)
## 
## Response: risk_cefaleia_resources
##     Df  Chisq Pr(&gt;Chisq)  
## sex  1 3.2606    0.07097 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="regressão-logística-binária.html#cb184-1"></a>base_uso <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb184-2"><a href="regressão-logística-binária.html#cb184-2"></a>janitor<span class="op">::</span><span class="kw">tabyl</span>(sex, risk_cefaleia_resources) <span class="op">%&gt;%</span><span class="st"> </span>janitor<span class="op">::</span><span class="kw">adorn_totals</span>(<span class="dt">where =</span> <span class="kw">c</span>(<span class="st">&quot;row&quot;</span>,<span class="st">&quot;col&quot;</span>))</span></code></pre></div>
<pre><code>##     sex   0  1 Total
##    Male 150  8   158
##  Female 162 19   181
##   Total 312 27   339</code></pre>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="regressão-logística-binária.html#cb186-1"></a>(<span class="kw">exp</span>(<span class="op">-</span><span class="fl">2.9311937</span>)<span class="op">*</span><span class="kw">exp</span>(<span class="fl">0.7880364</span>))<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span>(<span class="kw">exp</span>(<span class="op">-</span><span class="fl">2.9311937</span>)<span class="op">*</span><span class="kw">exp</span>(<span class="fl">0.7880364</span>)))</span></code></pre></div>
<pre><code>## [1] 0.1049724</code></pre>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="regressão-logística-binária.html#cb188-1"></a><span class="fl">0.05333333</span><span class="op">*</span><span class="fl">2.19907406</span><span class="op">/</span>(<span class="dv">1</span><span class="fl">+0.05333333</span><span class="op">*</span><span class="fl">2.19907406</span>)</span></code></pre></div>
<pre><code>## [1] 0.1049724</code></pre>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="regressão-logística-binária.html#cb190-1"></a><span class="co">#odds to probability</span></span>
<span id="cb190-2"><a href="regressão-logística-binária.html#cb190-2"></a><span class="co">#predict(mod_1, newdata=data.frame(sex=&quot;Female&quot;), type=&quot;response&quot;)</span></span></code></pre></div>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="regressão-logística-binária.html#cb191-1"></a>(<span class="dv">19</span><span class="op">*</span><span class="dv">150</span>)<span class="op">/</span>(<span class="dv">162</span><span class="op">*</span><span class="dv">8</span>)<span class="co">#odds of females have risk (compared to males)</span></span></code></pre></div>
<pre><code>## [1] 2.199074</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="regressão-logística-binária.html#cb193-1"></a><span class="dv">19</span><span class="op">/</span><span class="dv">181</span> <span class="co">#proportion of females with risk</span></span></code></pre></div>
<pre><code>## [1] 0.1049724</code></pre>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="regressão-logística-binária.html#cb195-1"></a><span class="dv">8</span><span class="op">/</span><span class="dv">158</span> <span class="co">#proportion of males with risk</span></span></code></pre></div>
<pre><code>## [1] 0.05063291</code></pre>
</div>
<div id="resumo-13" class="section level2">
<h2><span class="header-section-number">15.6</span> Resumo</h2>
<div class="explore">
<ol style="list-style-type: decimal">
<li>O termo regressão múltipla se refere a um modelo de regressão com duas ou mais variáveis independentes<br />
</li>
<li>As VIs podem ser de qualquer natureza, o que significa que toda família da ANOVA pode ser entendida como casos particulares de regressão</li>
<li>As estimativas geradas pela regressão múltipla para uma variável são controlam por todas as variáveis do modelo<br />
</li>
<li>Os diagnósticos são os mesmos dos modelos simples, mas agora é necessário também testar a multicolinearidade do modelo<br />
</li>
<li>Existem diferentes métodos para adicionar preditores e maneiras manuais e automáticas são disponíveis<br />
</li>
</ol>
</div>
</div>
<div id="pesquisas-adicionais-8" class="section level2">
<h2><span class="header-section-number">15.7</span> Pesquisas adicionais</h2>
<ol style="list-style-type: decimal">
<li>Influence of Age and Education on the Performance of Elderly in the Brazilian Version of the Montreal Cognitive Assessment Battery (DOI: 10.1159/000489774)
Nesta pesquisa, 110 participantes foram recrutados para que os pesquisadores pudessem produzir tabelas estatísticas para um novo exame neuropsicológico. Uma das análises feitas verificou o impacto dos anos de estudo no desempenho neste exame neuropsicológico, concluindo pelo seu efeito protetivo.</li>
</ol>
</div>
<div id="questões-4" class="section level2">
<h2><span class="header-section-number">15.8</span> Questões</h2>
<div class="question">
<ol style="list-style-type: decimal">
<li>(Retirado de Andy Field - Dicovering statistics) A regressão logística assume entre seus pressupostos<br>a) Relacionmento linear entre os preditores contínuos e a variável resposta.<br>b) Relacionmento linear entre os preditores contínuos e o logit da variável resposta.<br>c) Relacionamento linear entre os preditores contínuos.<br>d) Relacionamento linear entre todas as observações. <br>e) Todas as opções são incorretas.</li>
</ol>
</div>
<div class="mirror">
Gabarito: 1-b;
</div>

<div id="refs" class="references">
<div>
<p>Aguiar Neto, R. R. de. (2010). <em>Estatistica basica aplicada a administracao judiciaria</em>. Colecao Administracao Judiciaria.</p>
</div>
<div>
<p>Amarasingha, N., &amp; Dissanayake, S. (2014). Gender differences of young drivers on injury severity outcome of highway crashes. <em>Journal of Safety Research</em>, <em>49</em>, 113.e1–120. <a href="https://doi.org/10.1016/j.jsr.2014.03.004">https://doi.org/10.1016/j.jsr.2014.03.004</a></p>
</div>
<div>
<p>Amatori, S., Zeppa, S. D., Preti, A., Gervasi, M., Gobbi, E., Ferrini, F., Rocchi, M. B. L., Baldari, C., Perroni, F., Piccoli, G., Stocchi, V., Sestili, P., &amp; Sisti, D. (2020). Dietary habits and psychological states during COVID-19 home isolation in italian college students: The role of physical exercise. <em>Nutrients</em>, <em>12</em>(12), 3660. <a href="https://doi.org/10.3390/nu12123660">https://doi.org/10.3390/nu12123660</a></p>
</div>
<div>
<p>Babbie, E. R. (1990). <em>Survey research methods / earl babbie.</em> (2nd ed.). Wadsworth Pub. Co.</p>
</div>
<div>
<p>Baird, D. (1983). The fisher/pearson chi-squared controversy: A turning point for inductive inference. <em>The British Journal for the Philosophy of Science</em>, <em>34</em>(2), 105–118. <a href="https://doi.org/10.1093/bjps/34.2.105">https://doi.org/10.1093/bjps/34.2.105</a></p>
</div>
<div>
<p>Bandura, A., Ross, D., &amp; Ross, S. A. (1961). Transmission of aggression through imitation of aggressive models. <em>The Journal of Abnormal and Social Psychology</em>, <em>63</em>(3), 575–582. <a href="https://doi.org/10.1037/h0045925">https://doi.org/10.1037/h0045925</a></p>
</div>
<div>
<p>Barker, L. E., &amp; Shaw, K. M. (2015). Best (but oft-forgotten) practices: Checking assumptions concerning regression residuals. <em>The American Journal of Clinical Nutrition</em>, <em>102</em>(3), 533–539. <a href="https://doi.org/10.3945/ajcn.115.113498">https://doi.org/10.3945/ajcn.115.113498</a></p>
</div>
<div>
<p>Bergenholtz, C., MacAulay, S. C., Kolympiris, C., &amp; Seim, I. (2018). Transparency on scientific instruments. <em>EMBO Reports</em>, <em>19</em>(6). <a href="https://doi.org/10.15252/embr.201845853">https://doi.org/10.15252/embr.201845853</a></p>
</div>
<div>
<p>Borgatta, E. F., &amp; Bohrnstedt, G. W. (1980). Level of measurement. <em>Sociological Methods &amp; Research</em>, <em>9</em>(2), 147–160. <a href="https://doi.org/10.1177/004912418000900202">https://doi.org/10.1177/004912418000900202</a></p>
</div>
<div>
<p>Bursztyn, L., González, A., &amp; Yanagizawa-Drott, D. (2018). <em>Misperceived social norms: Female labor force participation in saudi arabia</em>. National Bureau of Economic Research. <a href="https://doi.org/10.3386/w24736">https://doi.org/10.3386/w24736</a></p>
</div>
<div>
<p>Campbell, I. (2007). Chi-squared and fisherIrwin tests of two-by-two tables with small sample recommendations. <em>Statistics in Medicine</em>, <em>26</em>(19), 3661–3675. <a href="https://doi.org/10.1002/sim.2832">https://doi.org/10.1002/sim.2832</a></p>
</div>
<div>
<p>Cassidy, S. A., Dimova, R., Giguère, B., Spence, J. R., &amp; Stanley, D. J. (2019). Failing grade: 89% of introduction-to-psychology textbooks that define or explain statistical significance do so incorrectly. <em>Advances in Methods and Practices in Psychological Science</em>, <em>2</em>(3), 233–239. <a href="https://doi.org/10.1177/2515245919858072">https://doi.org/10.1177/2515245919858072</a></p>
</div>
<div>
<p>Chartier, S., &amp; Faulkner, A. (2008). General linear models: An integrated approach to statistics. <em>Tutorials in Quantitative Methods for Psychology</em>, <em>4</em>(2), 65–78. <a href="https://doi.org/10.20982/tqmp.04.2.p065">https://doi.org/10.20982/tqmp.04.2.p065</a></p>
</div>
<div>
<p>Cohen, B. (2013). <em>Explaining psychological statistics</em>. John Wiley &amp; Sons.</p>
</div>
<div>
<p>Cohen, J. (1988). <em>Statistical power analysis for the behavioral sciences</em>. Routledge. <a href="https://doi.org/10.4324/9780203771587">https://doi.org/10.4324/9780203771587</a></p>
</div>
<div>
<p>Curley, K. (2013). Testing the assumptions of assumptions testing. <em>Casualty Actuarial Society</em>. <a href="https://www.casact.org/pubs/forum/13fforum/07-Curley.pdf">https://www.casact.org/pubs/forum/13fforum/07-Curley.pdf</a></p>
</div>
<div>
<p>Dumsday, T. (2012). Laws of nature dontHaveCeteris paribus clauses, TheyAreCeteris paribus clauses. <em>Ratio</em>, <em>26</em>(2), 134–147. <a href="https://doi.org/10.1111/rati.12000">https://doi.org/10.1111/rati.12000</a></p>
</div>
<div>
<p>Ernst, A. F., &amp; Albers, C. J. (2017). Regression assumptions in clinical psychology research practicea systematic review of common misconceptions. <em>PeerJ</em>, <em>5</em>, e3323. <a href="https://doi.org/10.7717/peerj.3323">https://doi.org/10.7717/peerj.3323</a></p>
</div>
<div>
<p>Everitt, B. (2002). <em>The cambridge dictionary of statistics</em>. Cambridge University Press. <a href="http://www.worldcat.org/search?qt=worldcat_org_all&amp;q=052181099X">http://www.worldcat.org/search?qt=worldcat_org_all&amp;q=052181099X</a></p>
</div>
<div>
<p>Feigelson, E. D., &amp; Babu, G. J. (Eds.). (1992). <em>Statistical challenges in modern astronomy</em>. Springer New York. <a href="https://doi.org/10.1007/978-1-4613-9290-3">https://doi.org/10.1007/978-1-4613-9290-3</a></p>
</div>
<div>
<p>Feil, E. G., Baggett, K., Davis, B., Landry, S., Sheeber, L., Leve, C., &amp; Johnson, U. (2020). Randomized control trial of an internet-based parenting intervention for mothers of infants. <em>Early Childhood Research Quarterly</em>, <em>50</em>, 36–44. <a href="https://doi.org/10.1016/j.ecresq.2018.11.003">https://doi.org/10.1016/j.ecresq.2018.11.003</a></p>
</div>
<div>
<p>Fennell, D. J. (2005). <em>A philosophical analysis of causality in econometrics.</em> [PhD thesis]. London School of Economics; Political Science.</p>
</div>
<div>
<p>Field, A. P., &amp; Wilcox, R. R. (2017). Robust statistical methods: A primer for clinical psychology and experimental psychopathology researchers. <em>Behaviour Research and Therapy</em>, <em>98</em>, 19–38. <a href="https://doi.org/10.1016/j.brat.2017.05.013">https://doi.org/10.1016/j.brat.2017.05.013</a></p>
</div>
<div>
<p>Fox, J. (2016). <em>Applied regression analysis and generalized linear models (3th edition)</em>. SAGE.</p>
</div>
<div>
<p>Frigg, R., &amp; Hartmann, S. (2020). Models in Science. In E. N. Zalta (Ed.), <em>The Stanford encyclopedia of philosophy</em> (Spring 2020). <a href="https://plato.stanford.edu/archives/spr2020/entries/models-science/">https://plato.stanford.edu/archives/spr2020/entries/models-science/</a>; Metaphysics Research Lab, Stanford University.</p>
</div>
<div>
<p>Friis, R. H., &amp; Selles, T. A. (2013). <em>Epidemiology for public health practice</em> (5nd ed.). Jones &amp; Barlett Publishers.</p>
</div>
<div>
<p>Gaudio, A. C., &amp; Zandonade, E. (2001). Proposição, validação e análise dos modelos que correlacionam estrutura química e atividade biológica. <em>Quimica Nova</em>, <em>24</em>(5), 658–671. <a href="https://doi.org/10.1590/s0100-40422001000500013">https://doi.org/10.1590/s0100-40422001000500013</a></p>
</div>
<div>
<p>Gil, A. C. (2002). <em>Como elaborar de projetos de pesquisa</em>. Editora Atlas S.A.</p>
</div>
<div>
<p>Glantz, S. A. (2014). <em>Principios de bioestatistica</em> (7 ed.). AMGH.</p>
</div>
<div>
<p>Goodman, S. N. (1999). Toward evidence-based medical statistics. 1: The p value fallacy. <em>Annals of Internal Medicine</em>, <em>130</em>(12), 995. <a href="https://doi.org/10.7326/0003-4819-130-12-199906150-00008">https://doi.org/10.7326/0003-4819-130-12-199906150-00008</a></p>
</div>
<div>
<p>Greenland, S. (2019). Valid p-values behave exactly as they should: Some misleading criticisms of p-values and their resolution with s-values. <em>The American Statistician</em>, <em>73</em>(sup1), 106–114. <a href="https://doi.org/10.1080/00031305.2018.1529625">https://doi.org/10.1080/00031305.2018.1529625</a></p>
</div>
<div>
<p>Gueorguieva, R., &amp; Krystal, J. H. (2004). Move over ANOVA. <em>Archives of General Psychiatry</em>, <em>61</em>(3), 310. <a href="https://doi.org/10.1001/archpsyc.61.3.310">https://doi.org/10.1001/archpsyc.61.3.310</a></p>
</div>
<div>
<p>Hayes, A. F. (n.d.). <em>Introduction to mediation, moderation, and conditional process analysis : A regression-based approach</em>. The Guilford Press.</p>
</div>
<div>
<p>Heidemann, L. A., Araujo, I. S., &amp; Veit, E. A. (2016). Modelagem didático-cientı́fica: Integrando atividades experimentais e o pro-cesso de modelagem cientı́fica no ensino de fı́sica. <em>Caderno Brasileiro de Ensino de Fı́sica</em>, <em>33</em>(1), 3. <a href="https://doi.org/10.5007/2175-7941.2016v33n1p3">https://doi.org/10.5007/2175-7941.2016v33n1p3</a></p>
</div>
<div>
<p>Hirschman, D. (2016). Stylized facts in the social sciences. <em>Sociological Science</em>, <em>3</em>, 604–626. <a href="https://doi.org/10.15195/v3.a26">https://doi.org/10.15195/v3.a26</a></p>
</div>
<div>
<p>Howell, D. C. (2011). <em>Fundamental Statistics for the Behavioral Sciences</em>. Wadsworth Cengage Learning.</p>
</div>
<div>
<p>Howell, D. C. (2011). <em>Fundamental statistics for the behavioral sciences (7th edition)</em>. Belmont.</p>
</div>
<div>
<p>Jones, C., &amp; Levin, J. (1994). Primary/elementary teachers’ attitudes toward science in four areas related to gender differences in students’ science performance. <em>Journal of Elementary Science Education</em>, <em>6</em>(1), 46–66. <a href="https://doi.org/10.1007/bf03170649">https://doi.org/10.1007/bf03170649</a></p>
</div>
<div>
<p>Junior, A. A., Almeida Portugal, A. C. de, Landeira-Fernandez, J., Bullón, F. F., Santos, E. J. R. dos, Vilhena, J. de, &amp; Anunciação, L. (2020). Depression and anxiety symptoms in a representative sample of undergraduate students in spain, portugal, and brazil. <em>Psicologia: Teoria E Pesquisa</em>, <em>36</em>. <a href="https://doi.org/10.1590/0102.3772e36412">https://doi.org/10.1590/0102.3772e36412</a></p>
</div>
<div>
<p>Krus, D. J., &amp; Krus, P. H. (1977). Lost: McCalls t scores: Why? <em>Educational and Psychological Measurement</em>, <em>37</em>(1), 257–261. <a href="https://doi.org/10.1177/001316447703700134">https://doi.org/10.1177/001316447703700134</a></p>
</div>
<div>
<p>Lecoutre, B., &amp; Poitevineau, J. (2014). <em>The significance test controversy revisited</em>. Springer Berlin Heidelberg. <a href="https://doi.org/10.1007/978-3-662-44046-9">https://doi.org/10.1007/978-3-662-44046-9</a></p>
</div>
<div>
<p>Lix, L. M., Keselman, J. C., &amp; Keselman, H. J. (1996). Consequences of assumption violations revisited: A quantitative review of alternatives to the one-way analysis of variance "f" test. <em>Review of Educational Research</em>, <em>66</em>(4), 579. <a href="https://doi.org/10.2307/1170654">https://doi.org/10.2307/1170654</a></p>
</div>
<div>
<p>Lumley, T., Diehr, P., Emerson, S., &amp; Chen, L. (2002). The importance of the normality assumption in large public health data sets. <em>Annual Review of Public Health</em>, <em>23</em>(1), 151–169. <a href="https://doi.org/10.1146/annurev.publhealth.23.100901.140546">https://doi.org/10.1146/annurev.publhealth.23.100901.140546</a></p>
</div>
<div>
<p>Matthews, R. (2000). Storks deliver babies ( p = 0.008). <em>Teaching Statistics</em>, <em>22</em>(2), 36–38. <a href="https://doi.org/10.1111/1467-9639.00013">https://doi.org/10.1111/1467-9639.00013</a></p>
</div>
<div>
<p>Michell, J. (1993). The origins of the representational theory of measurement: Helmholtz, hölder, and russell. <em>Studies in History and Philosophy of Science Part A</em>, <em>24</em>(2), 185–206. <a href="https://doi.org/10.1016/0039-3681(93)90045-l">https://doi.org/10.1016/0039-3681(93)90045-l</a></p>
</div>
<div>
<p>Morettin, P. A., &amp; Bussab, W. de O. (2010). <em>Estatistica basica</em>. Saraiva.</p>
</div>
<div>
<p>Motulsky, H. J. (2014). Common misconceptions about data analysis and statistics. <em>Naunyn-Schmiedebergs Archives of Pharmacology</em>, <em>387</em>(11), 1017–1023. <a href="https://doi.org/10.1007/s00210-014-1037-6">https://doi.org/10.1007/s00210-014-1037-6</a></p>
</div>
<div>
<p>Mujcic, R., &amp; Frijters, P. (2020). The colour of a free ride. <em>The Economic Journal</em>. <a href="https://doi.org/10.1093/ej/ueaa090">https://doi.org/10.1093/ej/ueaa090</a></p>
</div>
<div>
<p>Neal, J. W., &amp; Neal, Z. (2021). <em>Who are the childfree?</em> <a href="https://doi.org/10.31234/osf.io/57bjr">https://doi.org/10.31234/osf.io/57bjr</a></p>
</div>
<div>
<p>Ocaña-Riola, R. (2016). The use of statistics in health sciences: Situation analysis and perspective. <em>Statistics in Biosciences</em>, <em>8</em>(2), 204–219. <a href="https://doi.org/10.1007/s12561-015-9138-4">https://doi.org/10.1007/s12561-015-9138-4</a></p>
</div>
<div>
<p>Pearson, K. (1900). X. On the criterion that a given system of deviations from the probable in the case of a correlated system of variables is such that it can be reasonably supposed to have arisen from random sampling. <em>The London, Edinburgh, and Dublin Philosophical Magazine and Journal of Science</em>, <em>50</em>(302), 157–175. <a href="https://doi.org/10.1080/14786440009463897">https://doi.org/10.1080/14786440009463897</a></p>
</div>
<div>
<p>Piff, P. K., Stancato, D. M., Cote, S., Mendoza-Denton, R., &amp; Keltner, D. (2012). Higher social class predicts increased unethical behavior. <em>Proceedings of the National Academy of Sciences</em>, <em>109</em>(11), 4086–4091. <a href="https://doi.org/10.1073/pnas.1118373109">https://doi.org/10.1073/pnas.1118373109</a></p>
</div>
<div>
<p>Portugues, E. G. (2020). Lab notes for statistics for social sciences ii: Multivariate techniques. In <em>Statistics for Social Sciences II: Multivariate Techniques</em>. <a href="https://bookdown.org/egarpor/SSS2-UC3M/">https://bookdown.org/egarpor/SSS2-UC3M/</a></p>
</div>
<div>
<p>Privitera, G. J. (2016). <em>Statistics for the behavioral sciences</em>. SAGE.</p>
</div>
<div>
<p>Putnam, H. (1980). Models and reality. <em>Journal of Symbolic Logic</em>, <em>45</em>(3), 464–482. <a href="https://doi.org/10.2307/2273415">https://doi.org/10.2307/2273415</a></p>
</div>
<div>
<p>Quené, H., &amp; Bergh, H. van den. (2004). On multi-level modeling of data from repeated measures designs: A tutorial. <em>Speech Communication</em>, <em>43</em>(1-2), 103–121. <a href="https://doi.org/10.1016/j.specom.2004.02.004">https://doi.org/10.1016/j.specom.2004.02.004</a></p>
</div>
<div>
<p>Rhodes, N., &amp; Pivik, K. (2011). Age and gender differences in risky driving: The roles of positive affect and risk perception. <em>Accident Analysis &amp; Prevention</em>, <em>43</em>(3), 923–931. <a href="https://doi.org/10.1016/j.aap.2010.11.015">https://doi.org/10.1016/j.aap.2010.11.015</a></p>
</div>
<div>
<p>Rooney, B. J., &amp; Evans, A. N. (2019). <em>Methods in psychological research</em>. SAGE Publications, Inc. <a href="https://doi.org/10.4135/9781506384955">https://doi.org/10.4135/9781506384955</a></p>
</div>
<div>
<p>Skogli, E. W., Andersen, P. N., &amp; Isaksen, J. (2020). An exploratory study of executive function development in children with autism, after receiving early intensive behavioral training. <em>Developmental Neurorehabilitation</em>, <em>23</em>(7), 439–447. <a href="https://doi.org/10.1080/17518423.2020.1756499">https://doi.org/10.1080/17518423.2020.1756499</a></p>
</div>
<div>
<p>Smart, J. C. (1999). <em>Higher education: Handbook of theory and research</em>. Springer.</p>
</div>
<div>
<p>Stangor, C. (2010). <em>Introduction to psychology</em> (1nd ed.). Flatworld Knowledge.</p>
</div>
<div>
<p>Stevens, S. S. (1959). Measurement, psychophysics, and utility. In P. Churchman C. W. &amp; Ratoosh (Ed.), <em>Measurement: Definitions and theories</em> (pp. 18–63). Willey.</p>
</div>
<div>
<p>Stevens, S. S. (1946). On the theory of scales of measurement. <em>Science</em>, <em>103</em>(2684), 677–680. <a href="https://doi.org/10.1126/science.103.2684.677">https://doi.org/10.1126/science.103.2684.677</a></p>
</div>
<div>
<p>Sugianto, D. K. (2017). The moderating effect of age, income, gender, expertise, loyalty program, and critical incident on the influence of customer satisfaction towards customer loyalty in airline industry: A case of pt. X. <em>iBuss Management</em>, <em>5</em>(1), 70–83.</p>
</div>
<div>
<p>Thorndike, E. L. (1914). <em>Educational psychology, vol 3: Mental work and fatigue and individual differences and their causes.</em> Teachers College. <a href="https://doi.org/10.1037/13796-000">https://doi.org/10.1037/13796-000</a></p>
</div>
<div>
<p>Trafimow, D. (2019). A frequentist alternative to significance testing, p-values, and confidence intervals. <em>Econometrics</em>, <em>7</em>(2), 26. <a href="https://doi.org/10.3390/econometrics7020026">https://doi.org/10.3390/econometrics7020026</a></p>
</div>
<div>
<p>Unger, S. H., &amp; Hansch, C. (1973). Model building in structure-activity relations. Reexamination of adrenergic blocking activity of .Beta.-halo-.beta.-arylalkylamines. <em>Journal of Medicinal Chemistry</em>, <em>16</em>(7), 745–749. <a href="https://doi.org/10.1021/jm00265a001">https://doi.org/10.1021/jm00265a001</a></p>
</div>
<div>
<p>Velleman, P. F., &amp; Wilkinson, L. (1993). Nominal, ordinal, interval, and ratio typologies are misleading. <em>The American Statistician</em>, <em>47</em>(1), 65–72. <a href="https://doi.org/10.1080/00031305.1993.10475938">https://doi.org/10.1080/00031305.1993.10475938</a></p>
</div>
<div>
<p>Wasserstein, R. L., &amp; Lazar, N. A. (2016). The ASA statement on p-values: Context, process, and purpose. <em>The American Statistician</em>, <em>70</em>(2), 129–133. <a href="https://doi.org/10.1080/00031305.2016.1154108">https://doi.org/10.1080/00031305.2016.1154108</a></p>
</div>
<div>
<p>Weisberg, M. (2013). Three kinds of models. In <em>Simulation and similarity</em> (pp. 7–23). Oxford University Press. <a href="https://doi.org/10.1093/acprof:oso/9780199933662.003.0002">https://doi.org/10.1093/acprof:oso/9780199933662.003.0002</a></p>
</div>
<div>
<p>Wenke, R. J., Mickan, S., &amp; Bisset, L. (2017). A cross sectional observational study of research activity of allied health teams: Is there a link with self-reported success, motivators and barriers to undertaking research? <em>BMC Health Services Research</em>, <em>17</em>(1). <a href="https://doi.org/10.1186/s12913-017-1996-7">https://doi.org/10.1186/s12913-017-1996-7</a></p>
</div>
<div>
<p>Worley, H. (2006). <em>Road traffic accidents increase dramatically worldwide</em>. <a href="https://www.prb.org/roadtrafficaccidentsincreasedramaticallyworldwide/">https://www.prb.org/roadtrafficaccidentsincreasedramaticallyworldwide/</a></p>
</div>
<div>
<p>Wu, H., &amp; Leung, S.-O. (2017). Can likert scales be treated as interval scales?A simulation study. <em>Journal of Social Service Research</em>, <em>43</em>(4), 527–532. <a href="https://doi.org/10.1080/01488376.2017.1329775">https://doi.org/10.1080/01488376.2017.1329775</a></p>
</div>
<div>
<p>Yap, B. W., &amp; Sim, C. H. (2011). Comparisons of various types of normality tests. <em>Journal of Statistical Computation and Simulation</em>, <em>81</em>(12), 2141–2155. <a href="https://doi.org/10.1080/00949655.2010.520163">https://doi.org/10.1080/00949655.2010.520163</a></p>
</div>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Barker2015">
<p>Barker, L. E., &amp; Shaw, K. M. (2015). Best (but oft-forgotten) practices: Checking assumptions concerning regression residuals. <em>The American Journal of Clinical Nutrition</em>, <em>102</em>(3), 533–539. <a href="https://doi.org/10.3945/ajcn.115.113498">https://doi.org/10.3945/ajcn.115.113498</a></p>
</div>
<div id="ref-Ernst2017">
<p>Ernst, A. F., &amp; Albers, C. J. (2017). Regression assumptions in clinical psychology research practicea systematic review of common misconceptions. <em>PeerJ</em>, <em>5</em>, e3323. <a href="https://doi.org/10.7717/peerj.3323">https://doi.org/10.7717/peerj.3323</a></p>
</div>
<div id="ref-Lix1996">
<p>Lix, L. M., Keselman, J. C., &amp; Keselman, H. J. (1996). Consequences of assumption violations revisited: A quantitative review of alternatives to the one-way analysis of variance "f" test. <em>Review of Educational Research</em>, <em>66</em>(4), 579. <a href="https://doi.org/10.2307/1170654">https://doi.org/10.2307/1170654</a></p>
</div>
<div id="ref-portugues2020">
<p>Portugues, E. G. (2020). Lab notes for statistics for social sciences ii: Multivariate techniques. In <em>Statistics for Social Sciences II: Multivariate Techniques</em>. <a href="https://bookdown.org/egarpor/SSS2-UC3M/">https://bookdown.org/egarpor/SSS2-UC3M/</a></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="regressão-linear-múltipla.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/cjvanlissa/gitbook-demo/edit/master/12-regressao_logistica_binaria.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["gitbook-demo.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
