<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 Teste T | Métodos quantitativos em Psicologia com R e Rstudio</title>
  <meta name="description" content="This GitBook is an example of a GitBook for teaching. It can be adapted for specific courses. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 Teste T | Métodos quantitativos em Psicologia com R e Rstudio" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This GitBook is an example of a GitBook for teaching. It can be adapted for specific courses. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="cjvanlissa/gitbook-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 Teste T | Métodos quantitativos em Psicologia com R e Rstudio" />
  
  <meta name="twitter:description" content="This GitBook is an example of a GitBook for teaching. It can be adapted for specific courses. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Luis Anunciação (PUC-Rio), PhD" />


<meta name="date" content="2020-04-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estatística-descritiva.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/viz-0.3/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.1/grViz.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MQT em Psicologia com R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introdução</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#objetivo"><i class="fa fa-check"></i><b>1.1</b> Objetivo</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#bases"><i class="fa fa-check"></i><b>1.2</b> Bases</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#pacotes-e-sintaxes"><i class="fa fa-check"></i><b>1.3</b> Pacotes e sintaxes</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#aspectos-gerais"><i class="fa fa-check"></i><b>1.4</b> Aspectos gerais</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html"><i class="fa fa-check"></i><b>2</b> Estatística Descritiva</a><ul>
<li class="chapter" data-level="2.1" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#pesquisa"><i class="fa fa-check"></i><b>2.1</b> Pesquisa</a></li>
<li class="chapter" data-level="2.2" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#condições-gerais"><i class="fa fa-check"></i><b>2.2</b> Condições gerais</a></li>
<li class="chapter" data-level="2.3" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#verbos-do-dplyr"><i class="fa fa-check"></i><b>2.3</b> Verbos do dplyr</a></li>
<li class="chapter" data-level="2.4" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#tabelas"><i class="fa fa-check"></i><b>2.4</b> Tabelas</a></li>
<li class="chapter" data-level="2.5" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#gráficos"><i class="fa fa-check"></i><b>2.5</b> Gráficos</a></li>
<li class="chapter" data-level="2.6" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variável-discreta"><i class="fa fa-check"></i><b>2.6</b> 1 variável discreta</a></li>
<li class="chapter" data-level="2.7" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variável-contínua"><i class="fa fa-check"></i><b>2.7</b> 1 variável contínua</a></li>
<li class="chapter" data-level="2.8" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variáveis-com-vi-discreta"><i class="fa fa-check"></i><b>2.8</b> 2 variáveis com VI discreta</a></li>
<li class="chapter" data-level="2.9" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#variáveis-com-vi-contínua"><i class="fa fa-check"></i><b>2.9</b> 2 variáveis com VI contínua</a></li>
<li class="chapter" data-level="2.10" data-path="estatística-descritiva.html"><a href="estatística-descritiva.html#outros-gráficos"><i class="fa fa-check"></i><b>2.10</b> Outros gráficos</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="teste-t.html"><a href="teste-t.html"><i class="fa fa-check"></i><b>3</b> Teste T</a><ul>
<li class="chapter" data-level="3.1" data-path="teste-t.html"><a href="teste-t.html#pesquisa-1"><i class="fa fa-check"></i><b>3.1</b> Pesquisa</a></li>
<li class="chapter" data-level="3.2" data-path="teste-t.html"><a href="teste-t.html#execução-no-r"><i class="fa fa-check"></i><b>3.2</b> Execução no R</a></li>
<li class="chapter" data-level="3.3" data-path="teste-t.html"><a href="teste-t.html#tamanho-do-efeito"><i class="fa fa-check"></i><b>3.3</b> Tamanho do efeito</a></li>
<li class="chapter" data-level="3.4" data-path="teste-t.html"><a href="teste-t.html#teste-t-e-regressão"><i class="fa fa-check"></i><b>3.4</b> Teste T e regressão</a></li>
<li class="chapter" data-level="3.5" data-path="teste-t.html"><a href="teste-t.html#aspectos-matemáticos"><i class="fa fa-check"></i><b>3.5</b> Aspectos matemáticos</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="http://www.puc-rio.br/" target="blank">PUC-Rio</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Métodos quantitativos em Psicologia com R e Rstudio</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="teste-t" class="section level1">
<h1><span class="header-section-number">Capítulo 3</span> Teste T</h1>
<div class="objectives">
<p>
<strong>Objetivos do capítulo</strong><br />
1. Apresentar o teste T<br />
2. Discutir os pressupostos de execução do teste T<br />
3. Realizar gráficos relacionados à comparação de médias<br />
4. Apresentar e interpretar métricas de tamanho do efeito<br />
5. Dar exemplos relacionados à escrita dos resultados 6. Apresentar versões não paramétricas
</p>
</div>
<p>O Teste T é um teste estatístico frequentemente utilizado para testar hipóteses sobre <u>diferenças entre médias</u>. Por utilizar dados amostrais para estimar um parâmetro (<span class="math inline">\(\mu\)</span>), ele é um teste parâmetrico. Apenas por um preâmbulo histórico, a origem do Teste T remonta o artigo publicado em 1908 por William Gosset. Na época, em função de seu trabalho na cervejaria Guiness, ele não assinou o artigo, mas apenas usou seu pseudônimo <em>Student</em>, motivo pelo qual o teste T também é chamado de Teste T de Student. Estudantes de Psicologia e profissionais que trabalham com avaliação psicológica costumam ser deparados com uma métrica chamada “T score”, desenvolvido em 1939 por um professor de Psicologia (William Anderson McCall). É importante avisar que esta métrica não ter relação com os procedimentos inferenciais relacionados ao teste T <span class="citation">(<span class="citeproc-not-found" data-reference-id="McCall1939"><strong>???</strong></span>; <span class="citeproc-not-found" data-reference-id="Krus1977"><strong>???</strong></span>)</span>.</p>
<p>É possível estipular que o Teste T pode ser utilizado para comparar a média de uma amostra com a média populacional (<em>one sample t test</em>), ou quando se deseja comparar duas médias amostrais (<em>two samples t test</em>) ou um quando se compara duas médias de uma mesma amostra que foi investigada em dois momentos do tempo (<em>paired ou matched t test</em>).</p>
<p>Se assume os seguintes pressupostos funcionais à execução de um Teste T:</p>
<p><em>(i)</em> Os dados são aleatórios e representativos da população
<em>(ii)</em> a variável dependente é contínua
<em>(iii)</em> A distribuição dos resultados populacionais é assumida como normal</p>
<p>Quando se utiliza o Teste T para comparar os resultados de dois grupos, é também necessário que</p>
<p><em>(iv)</em> As variâncias dos grupos seja homogênea (princípio da homocedasticidade)
<em>(v)</em> ambos os grupos sejam independentes</p>
<p>Quando se utiliza o Teste T pareado, se viola o princípio da independência, mas é necessário que:
<em>(vi)</em> o tamanho amostral seja o mesmo</p>
<p>Eventualmente, quando os pressupos são violados, versões não-paramétricas podem ser implementadas. A tabela abaixo concatena os testes estatísticos relacionados e, para fins de comparação com outros trabalhos, há autores que sugerem que se use sempre as versões não-paramétricas em resultados obtidos por processos de avaliação psicológica, arguindo que os dados tem nível de medida “ordinal”.</p>
<table>
<thead>
<tr class="header">
<th align="left">Versão do teste</th>
<th align="left">Um grupo</th>
<th align="left">Dois grupos independentes</th>
<th align="left">Grupos pareados</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Paramétrica</td>
<td align="left">One-sample t test</td>
<td align="left">Two-samples t test</td>
<td align="left">Paired t test</td>
</tr>
<tr class="even">
<td align="left">Não-paramétrica</td>
<td align="left">Signed rank test</td>
<td align="left">Mann-whitney</td>
<td align="left">Wilcoxon</td>
</tr>
</tbody>
</table>
<div id="pesquisa-1" class="section level2">
<h2><span class="header-section-number">3.1</span> Pesquisa</h2>
<div class="alert alert-info" role="alert">
<p><strong>Base</strong> Livro - R - ASQ SE all age intervals</p>
</div>
<p>Neste capítulo, vamos utilizar a pesquisa intitulada “Confirmatory analysis and normative tables for the Brazilian Ages and Stages Questionnaires: Social–Emotional”, publciada em 2019 no Child Care Health Development. O objetivo da pesquisa se quebrou em dois eixos. O primeiro visando confirmar a estrutura fatorial de um instrumento utilizado para avaliar competências sociais e emocionais relacionadas ao desenvolvimento infantil e o segundo para gerar tabelas normativas ao desempenho obtido pelos meninos e meninas avaliados. Essa é uma pesquisa muito importante, uma vez que conta com uma base de dados robusta (mais de 50 mil participantes) e costura psicometria, avaliação psicológica e políticas públicas</p>
</div>
<div id="execução-no-r" class="section level2">
<h2><span class="header-section-number">3.2</span> Execução no R</h2>
<p>O teste T trabalha com variáveis contínuas e nessa base de dados, isso será feito pela soma de todos os itens da escala. No dplyr, isso é feito pela integração da função <code>mutate</code> com a <code>select</code></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1">asq_12months &lt;-<span class="st"> </span>asq_12months <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb45-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">total_12 =</span> <span class="kw">rowSums</span>(<span class="kw">select</span>(., <span class="kw">starts_with</span>(<span class="st">&quot;q_&quot;</span>)), <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</a></code></pre></div>
<p>Para comparar os resultados médios obtidos por meninos e meninas aos 12 meses, o teste T é uma opção frequente. Em relação à formalidade analítica, é necessário escrita adequada das hipóteses e o nível de significância adotado nesta análise. Dessa maneira:</p>
<p><span class="math display">\[H_0 = \mu_{meninos} - \mu_{meninas} = 0 \\ H_a = \mu_{meninos} - \mu_{meninas} \neq 0 \\ \alpha = 0.05\]</span></p>
<p>Em seguida, o processo de testagem da hipótese é feito preliminarmente de maneira gráfica e, em seguida, pela implementação do teste específico. Apesar do gráfico não ser decisivo na tomada de decisão, ele auxilia a visualilzação da distribuição da variável que temos interesse, bem como oferece já um entendimento inicial dos resultados.</p>
<p>Uma vez que a VI é discreta e a VD é continua (exposta no capítulo @ref(01-estatistica_descritiva)) tanto o gráfico de colunas/barras como o de densidade são úteis.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1">gridExtra<span class="op">::</span><span class="kw">grid.arrange</span>(</a>
<a class="sourceLine" id="cb46-2" title="2">  <span class="co">#plot 1 </span></a>
<a class="sourceLine" id="cb46-3" title="3">  <span class="kw">ggplot</span>(asq_12months, <span class="kw">aes</span>(<span class="dt">x =</span> sex, <span class="dt">y =</span> total_<span class="dv">12</span>, <span class="dt">fill =</span> sex)) <span class="op">+</span></a>
<a class="sourceLine" id="cb46-4" title="4"><span class="st">    </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;summary&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb46-5" title="5"><span class="st">    </span><span class="kw">stat_summary</span>(<span class="dt">fun.data =</span> mean_se, <span class="dt">geom =</span> <span class="st">&quot;errorbar&quot;</span>, <span class="dt">width =</span> <span class="fl">.2</span>),</a>
<a class="sourceLine" id="cb46-6" title="6">  <span class="co">#plot 2</span></a>
<a class="sourceLine" id="cb46-7" title="7">    <span class="kw">ggplot</span>(asq_12months, <span class="kw">aes</span>(<span class="dt">x =</span> total_<span class="dv">12</span>, <span class="dt">fill =</span> sex)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb46-8" title="8"><span class="st">    </span><span class="kw">geom_density</span>(<span class="dt">color =</span> <span class="ot">NA</span>, <span class="dt">alpha=</span>.<span class="dv">6</span>)</a>
<a class="sourceLine" id="cb46-9" title="9">)</a></code></pre></div>
<pre><code>## No summary function supplied, defaulting to `mean_se()</code></pre>
<p><img src="gitbook-demo_files/figure-html/unnamed-chunk-31-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Posto isso, o próximo passo é a testagem formal da hipótese. Como exposto, o teste T de duas amostras independentes assume que os resultados da variável de interesse se distribua normalmente e que variância entre os grupos seja homocedástica. Tecnicamente, como o teste T é um caso especial de um modelo de regressão, a normalidade da variável de interesse se refere aos resíduos do modelo e, neste caso pode ser testada pela distribuição marginal dos resultados de ambos os grupos.</p>
<p>A normalidade pode ser avaliada graficamente por QQ-plots e por testes específicos, como o Shapiro-wilk, Anderson-Darling e Jarque Bera.</p>
<p>O QQ plot é um gráfico que reúne a distribuição empírica ordenada dos quantis conta os quantis da distribuição teórica (aqui, normal). Se os dados e a linha diagonal se soprepuserem, isso é uma evidencia de que a distribuição empírica é a mesma da distribuição teórica. Caso haja discrepância, isso aponta para desvio da normalidade.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1"><span class="kw">ggplot</span>(asq_12months, <span class="kw">aes</span>(<span class="dt">sample =</span> total_<span class="dv">12</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb48-2" title="2"><span class="st">  </span><span class="kw">stat_qq</span>()  <span class="op">+</span><span class="st"> </span><span class="kw">stat_qq_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb48-3" title="3"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>sex)</a></code></pre></div>
<p><img src="gitbook-demo_files/figure-html/unnamed-chunk-32-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Apesar do gráfico já ter sido bastante claro e sugerir fortemente desvio da normalidade em ambos os grupos, o teste formal é necessário. O Shapiro-wilk costuma ser utilizado neste caso, uma vez que ele reúne diferentes características positivas no balanço entre erro do tipo 1 e 2.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1">asq_12months <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb49-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(sex) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb49-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">shapiro =</span> <span class="kw">shapiro.test</span>(total_<span class="dv">12</span>)<span class="op">$</span>p.value)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   sex    shapiro
##   &lt;fct&gt;    &lt;dbl&gt;
## 1 M     1.98e-19
## 2 F     4.80e-17</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1">t_test_12m &lt;-<span class="st"> </span><span class="kw">t.test</span>(total_<span class="dv">12</span> <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> asq_12months)</a></code></pre></div>
<p>Como frequentemente o pressuposto da homogeneidade das variâncias é violado, o R já executa por padrão a versão robusta do teste T (Welch test). Nesse caso, o valor de P do teste T é de 0.7124907, indicando pela não rejeição da hipótese nula. A apresentação abaixo traz o output do teste T.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1">t_test_12m</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  total_12 by sex
## t = 0.36861, df = 1037.4, p-value = 0.7125
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.072500  3.031252
## sample estimates:
## mean in group M mean in group F 
##        24.91713        24.43775</code></pre>
<div class="writing">
<p>
<strong>Como escrever os resultados</strong>
</p>
<p>
Os dados foram analisados por um Teste T para investigar as diferenças médias nos resultados do desenvolvimento entre meninos e meninas. Os resultados mostraram que os valores médios de meninos e meninas não não são significativamente diferentes (t(1037.4) = 0.368, p = 0.71). <strong>Dessa forma, as diferenças podem ser mais bem explicadas por outras fontes de variações.</strong>
</p>
</div>
<p>No entanto, é também possível verificar se existem diferenças em idades mais avançadas. A sintaxe é customizável e torna-se fácil testar a hipótese da diferença, por exemplo, aos 2 anos. Nesse sentido, o teste de hipóteses deve ser normalmente escrito:</p>
<p><span class="math display">\[H_0 = \mu_{meninos} - \mu_{meninas} = 0 \\ H_a = \mu_{meninos} - \mu_{meninas} \neq 0 \\ \alpha = 0.05\]</span></p>
<p>O gráfico novamente deve ser realizado</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1">plot_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">ggplot</span>(asq_18months, <span class="kw">aes</span>(<span class="dt">x =</span> sex, <span class="dt">y =</span> score, <span class="dt">fill =</span> sex)) <span class="op">+</span></a>
<a class="sourceLine" id="cb54-2" title="2"><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;summary&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb54-3" title="3"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data =</span> mean_se, <span class="dt">geom =</span> <span class="st">&quot;errorbar&quot;</span>, <span class="dt">width =</span> <span class="fl">.2</span>)</a>
<a class="sourceLine" id="cb54-4" title="4">plot_<span class="dv">4</span> &lt;-<span class="st"> </span><span class="kw">ggplot</span>(asq_18months, <span class="kw">aes</span>(<span class="dt">x =</span> score, <span class="dt">fill =</span> sex)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb54-5" title="5"><span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">color =</span> <span class="ot">NA</span>, <span class="dt">alpha=</span>.<span class="dv">6</span>)</a>
<a class="sourceLine" id="cb54-6" title="6"></a>
<a class="sourceLine" id="cb54-7" title="7">gridExtra<span class="op">::</span><span class="kw">grid.arrange</span>(plot_<span class="dv">3</span>, plot_<span class="dv">4</span>)</a></code></pre></div>
<pre><code>## No summary function supplied, defaulting to `mean_se()</code></pre>
<p><img src="gitbook-demo_files/figure-html/unnamed-chunk-37-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>E o teste formal computado:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1">t_test_18m &lt;-<span class="st"> </span><span class="kw">t.test</span>(score <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> asq_18months)</a>
<a class="sourceLine" id="cb56-2" title="2">t_test_18m</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  score by sex
## t = 4.6317, df = 5724.3, p-value = 3.707e-06
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  1.487790 3.671471
## sample estimates:
## mean in group M mean in group F 
##        27.52685        24.94722</code></pre>
<p>Diferentemente do anterior, agora o resultado foi significativo (p &lt; 0.01) e deve ser reportado:</p>
<div class="writing">
<p>
<strong>Como escrever os resultados</strong>
</p>
<p>
Os dados foram analisados por um Teste T para investigar as diferenças médias nos resultados do desenvolvimento entre meninos e meninas com 2 anos de idade. Os resultados mostraram que os valores médios de meninos (M = 27.5, SD = 21.8) e meninas (M = 24.9, SD = 20.3) são significativamente diferentes (t(5724.3) = -4.63, p &lt; 0.01).
</p>
</div>
<p>É importante ter uma atenção especial à significância estatística. De forma alguma, um resultado que rejeita a hipótese nula (como o de agora) deve ser entendido como “aceitação da hipótese alternativa”, tampouco como evidência de causalidade. É fundamental lembrar que o valor de P se refere à probabilidade de encontrar a estatística de teste calculada, ou uma ainda mais exterma, assumindo que a hipótese nula é verdadeira. Apesar de algo contra-intuitivo (e talvez desanimador), é assim que a estatística frequentista funciona.</p>
</div>
<div id="tamanho-do-efeito" class="section level2">
<h2><span class="header-section-number">3.3</span> Tamanho do efeito</h2>
<p>Resultados significativos não são nenhum pouco claros em relação ao tamanho do efeito. Essa métrica tem mais contato com as perguntas originalmente realizadas em uma pesquisa e é entendida como uma medida objetiva e padronizada da magnitude de um efeito observado independente da significância estatística.</p>
<p>Existem duas famílias principais no framework do tamanho do efeito, que são a família <code>d</code>e a família <code>r</code>. Tecnicamente, quando comparamos médias, usamos o d de cohen para calcular a distância entre as médias das distribuições normais sobrepostas.</p>
<p>A interpretação é a seguinte:</p>
<table>
<thead>
<tr class="header">
<th align="left">Cohen’s d</th>
<th align="left">Interpretação</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">d <span class="math inline">\(\geq\)</span> 0.8</td>
<td align="left">Alto</td>
</tr>
<tr class="even">
<td align="left">d <span class="math inline">\(\geq\)</span> 0.5</td>
<td align="left">Medio</td>
</tr>
<tr class="odd">
<td align="left">d <span class="math inline">\(\geq\)</span> 0.2</td>
<td align="left">Pequeno</td>
</tr>
<tr class="even">
<td align="left">d &lt; 0.2</td>
<td align="left">Irrelevante</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="kw">library</span>(effsize)</a>
<a class="sourceLine" id="cb58-2" title="2"><span class="kw">cohen.d</span>(score <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> asq_18months)</a></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: 0.12216 (negligible)
## 95 percent confidence interval:
##      lower      upper 
## 0.07025972 0.17406037</code></pre>
<p>Agora é possível agregar ambos os resultados e a escrita iria por esse caminho.</p>
<div class="writing">
<p>
<strong>Como escrever os resultados</strong>
</p>
<p>
Os dados foram analisados por um Teste T para investigar as diferenças médias nos resultados do desenvolvimento entre meninos e meninas com 2 anos de idade. Os resultados mostraram que os valores médios de meninos (M = 27.5, SD = 21.8) e meninas (M = 24.9, SD = 20.3) são significativamente diferentes (t(5724.3) = -4.63, p &lt; 0.01), apesar do tamanho do efeito ser negligenciável (d = 0.12)
</p>
</div>
</div>
<div id="teste-t-e-regressão" class="section level2">
<h2><span class="header-section-number">3.4</span> Teste T e regressão</h2>
<p>Conforme alertado, o Teste T nada mais é do que um modelo de regressão que assume que a variável independente é uma dummy. Assim, <span class="math inline">\(b_0\)</span> é o grupo que recebeu o valor 0 e <span class="math inline">\(b_1\)</span> é o grupo que recebeu o valor 1. Caso isso não tenha sido definido inicialmente, basta estipular que a variável é um <em>fator</em>, mesmo que de maneira implícita, e o R cuidará de todo o resto.</p>
<p>Nesse caso, o R atribuiu os meninos como intercepto o valor médio dos meninos e a inclinação <span class="math inline">\(b_1\)</span> é justamente a diferença entre os valores (<em>24.95-27.53)</em>. Nesse caso, -2.58. A estatística F é equivalente a <span class="math inline">\(t^2\)</span> do teste t em sua versão tradicional (assumindo que as variâncias dos grupos são igual, adicionando <code>var.equal = T</code> ao argumento)</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1"><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> asq_18months) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb60-2" title="2"><span class="st">  </span>stargazer<span class="op">::</span><span class="kw">stargazer</span>(., <span class="dt">type =</span> <span class="st">&quot;text&quot;</span>)</a></code></pre></div>
<pre><code>## 
## ===============================================
##                         Dependent variable:    
##                     ---------------------------
##                                score           
## -----------------------------------------------
## sexF                         -2.580***         
##                               (0.559)          
##                                                
## Constant                     27.527***         
##                               (0.387)          
##                                                
## -----------------------------------------------
## Observations                   5,727           
## R2                             0.004           
## Adjusted R2                    0.004           
## Residual Std. Error     21.117 (df = 5725)     
## F Statistic          21.331*** (df = 1; 5725)  
## ===============================================
## Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<div id="aspectos-matemáticos" class="section level2">
<h2><span class="header-section-number">3.5</span> Aspectos matemáticos</h2>

<div id="refs" class="references">
<div>
<p>Morettin, Pedro Alberto, and Wilton de Oliveira Bussab. 2010. <em>Estatistica Basica</em>. Saraiva.</p>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estatística-descritiva.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/cjvanlissa/gitbook-demo/edit/master/05-teste_t.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["gitbook-demo.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
